### ISSUE TITLE
Netflix not working

### ISSUE THREAD

**Issue by ROBdk97** [PreMiD/PreMiD#101]
**Describe the bug**
YouTube and YouTube Musik are working but Netflix not.

**To Reproduce**
1.For Netflix on Website not working
2. 
3.

**Expected behavior**
It working/ Showing what I watch

**Screenshots**
https://gyazo.com/487165a5629ee0bf1fe56f2fe30449ad
https://gyazo.com/0c1694df9c4154010d9513b90ebbfb7c

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 72.0.3626.64

**Additional context**

**Comment by Fruxh** [comment]
Hey @ROBdk97,

thank you for that bug report.

Netflix is working for me. Maybe you can fix it by taking a look at the #help channel in our Discord server.
Invite link: https://discord.gg/WvfVZ8T

Greetings
~Fruxh
