### ISSUE TITLE
Premid crash on hyprland

### ISSUE THREAD

**Issue by MidnightTale** [PreMiD/PreMiD#1030]
**Describe the bug**
premid crash after open in [hyprland](hyprland.org/) with nvidia card

**To Reproduce**
1.install premid with command yay -S premid
2.open premid
3.crash

**Expected behavior**
should run normal without crash after opened

**Screenshots**
![image](https://github.com/PreMiD/PreMiD/assets/125941391/1bc6c490-159d-4a93-8c2b-aebb17763d2a)

**Desktop (please complete the following information):**
 - OS: Archlinux x86_64
 - Browser [Floorp(Firefox base)]
 - Version [premid 2.3.4-1]

**Comment by jonasrdl** [comment]
Could you maybe provide a bit more technical details about graphics drivers etc.? Looks to me like some missing drivers or extensions, could be related to Vulkan

**Comment by MidnightTale** [comment]
i'm on nvidia 555.52.04 get this error 
![image](https://github.com/PreMiD/PreMiD/assets/125941391/b82728ef-616f-4b5e-bbe2-8afb2cea7574)
![image](https://github.com/PreMiD/PreMiD/assets/125941391/017b941d-8ea7-499b-b67f-8bfec5eb09f6)
i downgrade to 550.90.07 still the same as above
![image](https://github.com/PreMiD/PreMiD/assets/125941391/3ae84806-b1f0-4e0b-874d-9e1269f2a92a)


info about gpu
![image](https://github.com/PreMiD/PreMiD/assets/125941391/2885e4f5-cb98-4c4b-b348-2c574389751e)

env system
![image](https://github.com/PreMiD/PreMiD/assets/125941391/59c4248f-873a-4423-92a6-55ee993ab1a3)


glxgear work
![image](https://github.com/PreMiD/PreMiD/assets/125941391/aa2e5793-b1b8-4f2d-9d73-75c3b943a0d4)
