### ISSUE TITLE
Multiple Statuses not working after update [CRP]

### ISSUE THREAD

**Issue by Syrubun** [PreMiD/PreMiD#1034]
**Describe the bug**
I use Custom Rich Presence to enhance my profile, PreMiD is no longer displaying after the latest update if CRP is connected.

**Desktop**
 - OS: Windows 11
 - Brave
 - Version Latest

**Comment by tajito** [comment]
same here

**Comment by Timeraa** [comment]
PreMiD doesn't use the app anymore as it uses private Discord endpoints, games take priority, Discord bug not our fault.
