### ISSUE TITLE
Extension - Not connected

### ISSUE THREAD

**Issue by 4zexiss** [PreMiD/PreMiD#1037]
**Describe the bug**
App is not detecting extension

**To Reproduce**
1. Install like intended

**Expected behavior**
Should work

**Screenshots**
![image](https://github.com/PreMiD/PreMiD/assets/98905481/e4ceb871-ba88-49f3-8769-0333f9750b89)
![image](https://github.com/PreMiD/PreMiD/assets/98905481/7749ef42-bee1-43eb-a4e4-cbb5d9dc5e69)
![image](https://github.com/PreMiD/PreMiD/assets/98905481/62917136-0d8b-4af4-a888-210a97db57eb)
![image](https://github.com/PreMiD/PreMiD/assets/98905481/e4594410-4334-4b8d-abd1-216c32c32151)

**Desktop (please complete the following information):**
 - Clean Win11Pro
 - Edge
 - Version 125.0.2535.67

**Comment by 4zexiss** [comment]
fixed by itself🤷‍♂️

**Comment by 4zexiss** [comment]
not working again

**Comment by 4zexiss** [comment]
its works sometimes, but still showing extension not connected

**Comment by W8100** [comment]
Same issue for me

**Comment by tag27** [comment]
With version 2.6.0 of the extension, you no longer need to use the PreMiD app now. Just connect your Discord account to the extension.

**Comment by 4zexiss** [comment]
it works worse than with app for me personally. but there is now option to prefer app and it works as good as previously.
