### ISSUE TITLE
Adding a local presence no longer possible

### ISSUE THREAD

**Issue by Atlas7005** [PreMiD/PreMiD#1038]
**Describe the bug**
The [presence development docs](https://docs.premid.app/en/dev/presence#loading-your-presence) tell you to load a local presence by holding Shift in the popup window. This does not work in 2.6 for me.

The load presence does simply not appear.

**To Reproduce**
1. Install PreMiD
2. Open Popup.
3. Hold shift.

**Expected behavior**
Load Presence should appear in the Presences section.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (19045.4412)
 - Brave Browser v1.66.115 (Chromium v125.0.6422.112)
 - Version 2.6.0

**Comment by DarkVillager** [comment]
This is the case because of Manifest v3. There will be a dev extension for developers in the future.
