### ISSUE TITLE
Cannot link discord when Privacy Badger enabled.

### ISSUE THREAD

**Issue by paweenwat-man** [PreMiD/PreMiD#1040]
**Describe the bug**
When I completed Discord authorization with PreMiD, the extension still showed "Discord unlinked" regardless of how many times I repeatedly authorized again.

**To Reproduce**
1. Install and enable Privacy Badger.
2. Open the PreMiD extension and click "Link Discord".
3. Discord authorization shows up and authorizes access to my account.
4. Repeat from Step 2.

**Expected behavior**
PreMiD extension should linked with my Discord.

**Screenshots**
![image](https://github.com/PreMiD/PreMiD/assets/82842156/6956bceb-0da7-4d56-887d-8aba4b991d81)

**Desktop (please complete the following information):**
 - Windows 11 Pro 23H2 22631.3593
 - Chrome 
 - 125.0.6422.142 (Official Build) (64-bit)

**Comment by joerkig** [comment]
Presumably related to EFForg/privacybadger#2968

**Comment by paweenwat-man** [comment]
I did a network logging and found out that the PreMiD extension tried to request [https://discord.com/api/v10/users/@me/headless-sessions](url), after that, I had to check about tracking domains in Privacy Badger Options and it blocked the domain completely. I set it back to allow the domain except for the cookie, the PreMiD extension goes back online.

Thanks.

![image](https://github.com/PreMiD/PreMiD/assets/82842156/039148fe-2c9c-4d1a-9af7-26e4d59542ec)
