### ISSUE TITLE
[Documentation?] Download Application Link on v2.2.0 Release page is Misspelt 

### ISSUE THREAD

**Issue by ChrisIsEditing** [PreMiD/PreMiD#1071]
_**Describe the bug**_
on v2.2.0's [release page](https://github.com/PreMiD/PreMiD/releases/tag/app-v2.2.0), the Application Download Link (_or text that reads "our website"_), links to /Download instead of /Download**s** on the website, sending persons to broken page.

Current Link: **https://premid.app/download**

_**Expected behavior**_
It should link to /Downloads. Which is the correct download link.

Correct Link: **https://premid.app/downloads**

_**Screenshots**_
![image 1](https://github.com/user-attachments/assets/cb7dab41-370a-44bc-bc4e-704f9cef8597)
![image 2](https://github.com/user-attachments/assets/05a2e2fb-23ef-4e92-89b5-31f0dd4e2deb)

**Comment by Timeraa** [comment]
The releases are only for the application which is deprecated now. You don't need it to use PreMiD
