### ISSUE TITLE
Rabb.it Presence seems broken after their site update

### ISSUE THREAD

**Issue by WolfNT90** [PreMiD/PreMiD#109]
**Describe the bug**
Rabb.it has recently updated their web platform, and as a result, I no longer see my presence on Discord being updated with that of rabb.it.

**To Reproduce**
1. Opening the homepage of rabb.it
2. Entering a room on rabb.it.

**Expected behavior**
On all previous visits to the homepage, it would immediately switch my presence to display "Browsing...", but it doesn't happen any more. Also, entering rooms does not seem to update the presence, either.

**Screenshots**
None

**Desktop**
 - OS: Xubuntu 18.10
 - Browser Mozilla Firefox (also tested with Google Chrome Stable)
 - Version of extension is 1.3.1.2 / Version of app is 1.2

**Additional context**
None

**Comment by Timeraa** [comment]
We released a hotfix until V2.0. Closing this issue.

Thanks for telling us!
