### ISSUE TITLE
Presence not displaying

### ISSUE THREAD

**Issue by Fox3n** [PreMiD/PreMiD#111]
**Describe the bug**
the presence does not display in discord for unknown reasons.

**To Reproduce**
1. Install app and extension
2. Check if they are running (they are)
3. Open a service
4. Not working presence

**Expected behavior**
It should appear in your status

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN
 - Browser Chrome
 - Version 

**Additional context**

**Comment by DooML** [comment]
Try https://github.com/PreMiD/PreMiD/wiki/Troubleshooting

And also :

- Enable "Display currently running game as a status message." in _Settings / Game Activity_

- Change the browser to Firefox

- In Chrome ( or any chromium based browser ), go to **chrome://startpage/extensions** and make sure if "Allow on all websites" is working

**Comment by Fruxh** [comment]
I'll add that to the wiki

**Comment by Fox3n** [comment]
> Try https://github.com/PreMiD/PreMiD/wiki/Troubleshooting
> 
> And also :
> 
> * Enable "Display currently running game as a status message." in _Settings / Game Activity_
> * Change the browser to Firefox
> * In Chrome ( or any chromium based browser ), go to **chrome://startpage/extensions** and make sure if "Allow on all websites" under the extension is enabled

Display status is on, it worked on chrome (but i'll try to update it), it's allowed on all websites

**Comment by DooML** [comment]
So did it work? and if so, which one solved it?

**Comment by Fox3n** [comment]
> So did it work? and if so, which one solved it?

nope it didn't. Chrome is updated now. "chrome://startpage/extensions" is not working

**Comment by Timeraa** [comment]
Closing this as we did not get any answer.

**Comment by AnakoniAurum** [comment]
j

**Comment by maciejkamo20** [comment]
got the same rn on opera gx lol

**Comment by maciejkamo20** [comment]
worked properly before on chrome, but now it doesnt work

**Comment by maciejkamo20** [comment]
im pretty sure i t also worked on opera gx

**Comment by SouhaylTP** [comment]
> worked properly before on chrome, but now it doesnt work

for me too ''

**Comment by Arcadiac69** [comment]
Hey guys, I think I figured out how to fix this!
In User Settings, click on Registered Games
Once you do so, click "Not seeing your game? Add it!"
After you do so, you should have a option to pick whichever browser you want to use, and that should do it!

**Comment by ShitaraRimule** [comment]
> Hé les gars, je pense que j'ai compris comment résoudre ce problème! Dans Paramètres utilisateur, cliquez sur Jeux enregistrés Une fois que vous l'avez fait, cliquez sur "Vous ne voyez pas votre jeu ? Ajoutez-le !" Après cela, vous devriez avoir la possibilité de choisir le navigateur que vous souhaitez utiliser, et cela devrait le faire !

in discord right ?
