### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by Joshuartje** [PreMiD/PreMiD#114]
Before reading this, this is to meme around in servers and have a bit of fun. It's for a fun joke, so kinda take this serious.

**What's the name of the service?**
pornhub.com | Pornhub

**What should the Presence display?**
What video you are watching, maybe with a picture of the thumbnail of the video, duration of the video, and maybe maybe the tags of the video. 

**Why do you want support for this service?**
Because I want to troll in servers by letting them think that this is a thing on Discord. Making them believe that I have no idea that it shows on Discord that I am playing this. Haha.

**Are you able to provide an image for the service? (512x512 minimum)**
This is easy to find on the internet, just google: pornhub.com

I kinda hope this gets accepted. Maybe in a private build, not public. Would love to troll around in servers with it haha.

**Comment by Fruxh** [comment]
This exits already....
Duplicate of #87

**Comment by Fruxh** [comment]
But thanks for the suggestion xD

**Comment by Joshuartje** [comment]
Haha i didn't look into it XD

**Comment by Timeraa** [comment]
Going to close this as its a dupe
