### ISSUE TITLE
Add support for Crunchyroll HTML5 Extension 

### ISSUE THREAD

**Issue by Scottydelfox13** [PreMiD/PreMiD#115]
**Is your feature request related to a problem? Please describe.**
The rich presence for crunchyroll fails to work when using [this extension](https://chrome.google.com/webstore/detail/crunchyroll-html5/ihegfgnkffeibpmnajnoiemkcmlbmhmi?utm_source=chrome-ntp-icon)

**Describe the solution you'd like**
add support for this extension

**Describe alternatives you've considered**
If the extension cant find a timestamp, but can find other information, just skip showing the timestamp, or just show a warning when this extension is installed

**Comment by Fruxh** [comment]
Just don't use this extension xD

**Comment by DooML** [comment]
The extension alters the style, that is why it blocks the rich presence from working properly. But I'll still take a look at it even though it's not on our end.

**Comment by Timeraa** [comment]
Closing this as we are not actively working on supporting extensions as described by @DooML alter the style.
