### ISSUE TITLE
Only use media controls if needed

### ISSUE THREAD

**Issue by TrojanerHD** [PreMiD/PreMiD#117]
**My problem**
It is really annoying for me that I have to manually switch the media controls off every time I do not use the feature. Because otherwise the program prevents all other programs (e. g. Spotify) from getting noticed if the media control buttons were pressed. (Is that understandable? I am not a native English speaker...)

**Solution proposal**
If there is no tab in focus by PreMiD currently then automatically deactivate the media controls.
By the way this could be integrated in the options; maybe as a slider with the options: "Always off | On if tab is focused by PreMiD | Always on" if that is possible.

**Comment by MulverineX** [comment]
This is fixed in 2.0
