### ISSUE TITLE
Twitch.tv not working

### ISSUE THREAD

**Issue by GreepTheSheep** [PreMiD/PreMiD#121]
**Describe the bug**
I opened a Twitch.tv Stream and I have no presence.

**To Reproduce**
1. Open a Twitch.tv stream
2. Check presence in Discord
3. No presence

Screens : 
On Twitch : https://image.noelshack.com/fichiers/2019/10/7/1552239285-2019-03-10.png
On YT : https://image.noelshack.com/fichiers/2019/10/7/1552239406-2019-03-10-1.png

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser : Chrome 72.0.3626.121
 - Version : 1.2

**Additional context**
I have Discord PTB, not normal Discord

**Comment by Timeraa** [comment]
Fixed in V2.0

**Comment by Timeraa** [comment]
We released a hotfix until V2.0. Closing this issue.

Thanks for telling us!

**Comment by DanTheManTV** [comment]
Same issue

**Comment by GreepTheSheep** [comment]
Old version, please re-open a issue with the new version if you're not on 1.2
