### ISSUE TITLE
Twitch TV Bug Title (after hotfix updated)

### ISSUE THREAD

**Issue by waritxx** [PreMiD/PreMiD#127]
Title bug.
It should be a title of streaming.
It be. and It will change to "Subscribe to .....(twitch username)......
**To Reproduce**
1.Press F5 it solved but it will change to "Subscribe to .. " again.
(edit)2.Exit and open Premid Application. It solve and again. (it took for a while like 10 minutes)
**Desktop (please complete the following information):**
Chrome 3.0.3683.86 (Official Build) (64-bit)

![Screenshot_12](https://user-images.githubusercontent.com/18569094/54999683-628c5a00-5003-11e9-99fb-2a0dd659a84c.png)
![Screenshot_13](https://user-images.githubusercontent.com/18569094/54999687-63bd8700-5003-11e9-86c2-0591c39b07dd.png)
![Screenshot_14](https://user-images.githubusercontent.com/18569094/54999689-65874a80-5003-11e9-972c-5ff31b4c0c54.png)
![Screenshot_15](https://user-images.githubusercontent.com/18569094/54999884-d0d11c80-5003-11e9-8b6d-2f47784c14a4.png)

sorry for my bad english.

**Comment by DooML** [comment]
@Fruxh ^
also, rip #github-issues ?

**Comment by Fruxh** [comment]
We released a hotfix (again) until V2.0. Closing this issue.

Thanks for telling us!
