### ISSUE TITLE
Allow hiding of status in top bar (Mac)

### ISSUE THREAD

**Issue by emiflake** [PreMiD/PreMiD#135]
On a Mac machine, the PreMiD application will show a title on the status bar
Like so:
![image](https://user-images.githubusercontent.com/7753922/56455270-93d71c00-635c-11e9-91ee-1e6297c77665.png)
This is cool and useful, but takes up a lot of space. It would be useful to be able to toggle this functionality in some sort of settings view under the menu: 
![image](https://user-images.githubusercontent.com/7753922/56455278-aea99080-635c-11e9-9a07-926963f81608.png)
Currently, (depending on the song) it takes up up to half of my top bar (which is already quite cluttered). It would be a great feature to have.

**Comment by Timeraa** [comment]
In your browser, click on the extension icon and then toggle "Title Menubar" it should disable it. If it doesn't work then welp, V2.0 is almost here

**Comment by Timeraa** [comment]
Closing this as no response
