### ISSUE TITLE
Automatically pause music players when starting a video

### ISSUE THREAD

**Issue by theLMGN** [PreMiD/PreMiD#136]
**Is your feature request related to a problem? Please describe.**
Whenever I watch a video on YouTube, I have to go to the icon in my Dock, and hit pause

**Describe the solution you'd like**
Whenever a video starts, stop iTunes, Spotify, etc

**Describe alternatives you've considered**
Background Music for macOS which stops with any system sound, which includes games which I don't want stopped, or random sound effects

**Additional context**
This could be possible by checking status of music players, and simulating a play/pause keypress, or natively communicating with apps, such as on macOS you can use the following command `osascript -e "tell application "iTunes" to pause"`

**Comment by Timeraa** [comment]
So umm, if i understand right you want to make PreMID stop all audio sources instead of YouTube etc?

**Comment by theLMGN** [comment]
@Timeraa Correct. If I have music on the Spotify app, and open a YouTube video, it should stop

**Comment by Voknehzyr** [comment]
> @Timeraa Correct. If I have music on the Spotify app, and open a YouTube video, it should stop

That's almost impossible to make, It will require a lot of code and will be working with lags.
Only one thing that might be possible is stopping music and videos in non-prioritized tabs, but this feature is not currently planned in future updates.

**Comment by theLMGN** [comment]
@Voknehzyr https://github.com/onetune/spotify-web-helper ?

**Comment by Voknehzyr** [comment]
> and as I said, AppleScript exists on macOS

We're developing our software not only for macOS but for Windows and Linux, so if there's no way to make this function work on other operating systems we won't be adding it.

**Comment by theLMGN** [comment]
@Voknehzyr The link to the Spotify Web Helper library works on Linux, Windows and macOS.

**Comment by Voknehzyr** [comment]
> @Voknehzyr The link to the Spotify Web Helper library works on Linux, Windows and macOS.

What about other services?

**Comment by Timeraa** [comment]
Going to close this as i don’t see a lot of demand for that plus all the coding involved is just too much to handle „alone“. Reopen if this changes.
