### ISSUE TITLE
Feature to allow user added websites

### ISSUE THREAD

**Issue by lanes100** [PreMiD/PreMiD#137]
I was thinking something like how Discord already has for individual programs. For example, let's say I want to add a certain website that isn't already listed and might not necessarily be an audio/visual service, but I want to display it nonetheless; I would just click a button in the extension that says "enable presence with this site" along with a place to upload an image so that the program can pull that image and use it on the rich presence indicator. 

Moreover, in the future a possible implementation of this on HTML5/Flash videos could be implemented, and the user could contribute to a possible community store of sorts where you could have user created services that are uploaded for other users to use. This would eliminate the need for so many GitHub requests and would make the extension basically self sufficient.

**Comment by Fruxh** [comment]
Hello @lanes100,

we're already working on a thing like a presence store -> #35 
Users can add their own presences there and publish them for the public.
Your idea is possible but takes a lot of time to code. We'll look into it when we got spare time ^^

Greetings
~ Fruxh
