### ISSUE TITLE
image corrupt for discord presence 

### ISSUE THREAD

**Issue by xocalibrun** [PreMiD/PreMiD#138]
Image for discord rich presence corrupt (play button)
<img width="241" alt="Screenshot 2019-05-02 at 16 17 56" src="https://user-images.githubusercontent.com/49354096/57086384-ea960b80-6cf5-11e9-993e-cf597a379c35.png">
<img width="240" alt="Screenshot 2019-05-02 at 16 18 02" src="https://user-images.githubusercontent.com/49354096/57086393-eec22900-6cf5-11e9-96e0-ded7a4ea0080.png">
On mac, chrome, version 1.2

**Comment by Timeraa** [comment]
Its a cache error, Discord's CDN & Cache is being weird...
