### ISSUE TITLE
YouTube will not be detected with Polymer Disabling Tampermonkey Script

### ISSUE THREAD

**Issue by BluebellGamer** [PreMiD/PreMiD#142]
**Describe the bug**

**To Reproduce**
1.Installed Tampermonkey Script to get back to the old version of youtube (Polymer Disable)
2.Opened a youtube video
3.PreMiD Fails to recognize what i am watching

**Expected behavior**
I expected it to work, it's still youtube

**Screenshots**
https://gyazo.com/3e75fb4f85dc88998a94022822a5cd66 (The Tampermonkey script)
https://gyazo.com/890c0b22b04584896d53c0062eb22de2 (PreMiD Not detecting)
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 
 - Browser [e.g. chrome, safari]Chrome
 - Version [e.g. 22] 74.0.3729.169

**Additional context**

**Comment by xPazz** [comment]
PreMiD only supports the new YouTube layout.

**Comment by Timeraa** [comment]
Closing this as solved.
