### ISSUE TITLE
Sometimes the extension's options window is not showing up on Firefox

### ISSUE THREAD

**Issue by TrojanerHD** [PreMiD/PreMiD#146]
**Describe the bug**
When I click on the extension icon in the upper right corner of Firefox then sometimes there is just an empty box

**To Reproduce**
1. Install Firefox and install the extension from [your post on Discord](https://discordapp.com/channels/493130730549805057/518467470894563345/561734911208194078)
2. Click on the PreMiD-icon in the upper right corner of Firefox.

**Expected behavior**
It should open the extension's option window.

**Screenshots**
![image](https://user-images.githubusercontent.com/32276754/58665594-85076000-8331-11e9-84ab-5828876cd6d6.png)

**Desktop**
 - OS: Windows 10 
 - Browser: Firefox Quantum 67.0 (64-bit)

**Comment by TrojanerHD** [comment]
I just found out that every second time I click on the extension this empty box appears instead of the options menu.

**Comment by DooML** [comment]
@TrojanerHD That's an issue wih Firefox's design, extensions that load external assets (such as the credits tab in this case) take time to completely appear, just like a website.
It usually would pop-up the second/third time you click it.

**Comment by Timeraa** [comment]
Does this still happen?

**Comment by TrojanerHD** [comment]
Nope. It happened for the one session of Firefox. But since it happened once it could happen again.

**Comment by Timeraa** [comment]
Idk, as i recoded the Extension in V2.0 which currently runs through beta testing. But i guess we’ll see.
