### ISSUE TITLE
PreMiD Stable | Vulnerability warnings

### ISSUE THREAD

**Issue by zKilluaGamer** [PreMiD/PreMiD#147]
**Describe the bug**
PreMiD is getting some errors when I start the src folder and has a lot of vulnerabilities.

**To Reproduce**
1. npm i
2. npm run start

**Expected behavior**
The dependencies are old.

**Screenshots**
http://prntscr.com/nwfa6n
http://prntscr.com/nwfaf3

**Solution**
Update the dependencies

OLD

"dependencies": {
    "auto-launch": "^5.0.5",
    "chalk": "^2.4.1",
    "discord-rpc": "^3.0.1",
    "electron-squirrel-startup": "^1.0.0",
    "electron-store": "^2.0.0",
    "express": "^4.16.4",
    "request": "^2.88.0",
    "socket.io": "^2.2.0"
  },
  "devDependencies": {
    "electron-prebuilt-compile": "3.0.2"
  }

NEW
"dependencies": {
    "auto-launch": "^5.0.5",
    "chalk": "^2.4.2",
    "discord-rpc": "^3.0.2",
    "electron-squirrel-startup": "^1.0.0",
    "electron-store": "^3.2.0",
    "express": "^4.17.1",
    "request": "^2.88.0",
    "socket.io": "^2.2.0"
  },
  "devDependencies": {
    "electron": "^5.0.2"
  }

**Comment by zKilluaGamer** [comment]
When I updated the dependencies worked at the same older without vulnerabilities or errors.

**Comment by HeemPlayz** [comment]
This app is a scam, just to gather information about you

**Comment by Fruxh** [comment]
Proof it :)

**Comment by Voknehzyr** [comment]
@zKilluaGamer This is normal practice in Node, when you're not updating the dependencies for too long. We're still developing the program and extension, so the code that are posted on GitHub may have problems with vulnerabilities and errors. Right now we're working on 2.0 version, and we will get rid of these problems in it.

**Comment by Timeraa** [comment]
^ every dependency in 2.0 is up to date
