### ISSUE TITLE
Foobar2k

### ISSUE THREAD

**Issue by O-YamaBullShit** [PreMiD/PreMiD#153]
**What's the name of the service?**
Ex. www.youtube.com | Foobar2000

**What should the Presence display?**
Info about the song is played

**Why do you want support for this service?**
Because it's the most great sound player (for me) and even it's not the most used I want it supported

**Comment by Janmeeba** [comment]
If you want to show in your Discord playing status what you are listening to in foobar2000, there is already this fb2k plugin for that:

https://github.com/NaamloosDT/foo_discord

I have been using it for quite a long time already and can say it does its job perfectly. :D

**Comment by Timeraa** [comment]
Closing this as it seems like this is an application, we can only support websites as of right now.
