### ISSUE TITLE
PreMiD Firefox Extension - Closes and deletes itself as soon as I run V2.0

### ISSUE THREAD

**Issue by danielrbickerdike** [PreMiD/PreMiD#162]
**Describe the bug**
PreMiD works absolutely fine on 1.2 for me, but after I download V2.0 after deleting PreMiD from both Local and Roaming of 1.2, The PreMiD firefox extension deletes itself and closes down the extension page. The app works fine if I am not running 2.0 however, it comes up with the extension page saying that I need to have the app running, its only once I run the app where the extension deletes itself.

**To Reproduce**
1. Download PreMiD V2.0 beta
2. Run the extension first without the app, notice how it's still on firefox?
3. Run the executable for the app.
4. As PreMiD runs, the whole firefox extension disappears

**Expected behavior**
I expected to have PreMiD boot up and show its UI in the addon section.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Version 67.0.4 (64-bit)

**Additional context**
Tried all troubleshooting steps including the disabling of all extensions.

**Comment by frozaum** [comment]
the PreMiD v2.0 beta is only available to people who donated/boosted the server

**Comment by Timeraa** [comment]
Gonna close this as solved
