### ISSUE TITLE
support for <video> and <audio> HTML

### ISSUE THREAD

**Issue by ManshionProd** [PreMiD/PreMiD#169]
**Is your feature request related to a problem? Please describe.**
a very large number of sites use "the reader" integrated in html5 (<video< and <audio<), but PreMID does not take this into account.

**Describe the solution you'd like**
It would be really convenient ( and for users, but also for you, to avoid making a special support for each site using these tags) that when on a page a video or audio is launched, PreMID indicates the name of the load file (preferences via metadata, and not the name "raw") and the site we are at.

**Describe alternatives you've considered**
I don't think there are any, except if there is another tag allowing it, or a native JS script allowing to play videos, or any other.

**Additional context**
https://www.w3schools.com/tags/tag_audio.asp
https://www.w3schools.com/tags/tag_video.asp

PS: sorry for my bad english, I hope you understand

**Comment by Timeraa** [comment]
PreMiD Presence Scripts are JS scripts which get injected into the tab, they have full HTML and JS access to them. Going to close this, if i understood something wrong, reopen.
