### ISSUE TITLE
add please yummyanime.club

### ISSUE THREAD

**Issue by DivineGSocketUser** [PreMiD/PreMiD#173]
**What's the name of the service?**
Ex. yummyanime.club | YummyAnime

**What should the Presence display?**
Informations about the current anime

**Why do you want support for this service?**
It`s my favourite anime site and most russia people watch anime there

**Are you able to provide an image for the service? (512x512 minimum)**
https://pp.userapi.com/c841224/v841224642/46d23/7LyH_W6Ywuw.jpg

**Comment by Voknehzyr** [comment]
https://github.com/PreMiD/PreMiD/issues/160
