### ISSUE TITLE
Categorize Presences

### ISSUE THREAD

**Issue by sustox** [PreMiD/PreMiD#177]
**Is your feature request related to a problem? Please describe.**
With the amount of presences being worked on/requested, it'd be great if there were a fix to the inevitable huge list to scroll down.

**Describe the solution you'd like**
Add categories to the list of presences and their toggles, e.g. "Anime", "Music", "TV & Movies", and more. An ability to favorite presences would also be extremely beneficial, if there's going to be so many.

**Describe alternatives you've considered**
Eh, not really any others.

**Comment by Timeraa** [comment]
Done in v2.0
