### ISSUE TITLE
Cant use presence shop with 2.0

### ISSUE THREAD

**Issue by BarterClub** [PreMiD/PreMiD#179]
**Describe the bug**

**To Reproduce**
Using both 2.0 for chrome and windows. 
go to the website to add presences
not allowed to use any according to the website. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser  chrome,Version 75.0.3770.142
 - Version 2.0

**Additional context**

**Comment by Timeraa** [comment]
Yeah its because the website is currently on master branch on both stable and beta, I will release a new beta really soon. For now you can go to ``chrome://extensions`` enable developer mode, click on background page and enter ``addPresence("YouTube")``

**Comment by Timeraa** [comment]
Closing this as you can now add them back by going to https://premid.app/store
