### ISSUE TITLE
Service Request - 9Anime

### ISSUE THREAD

**Issue by Flowyan** [PreMiD/PreMiD#180]
**What's the name of the service?**
9anime.ru | 9Anime

**What should the Presence display?**
What anime episode im watching, what anime im watching, how long until the episode ends, basically the same like on youtube

**Why do you want support for this service?**
So people on discord see what anime im watching and because some of the shows aren't on crunchyroll or the others, the presence doesnt show what im watching because i use 9anime.

**Are you able to provide an image for the service? (512x512 minimum)**
https://lh3.googleusercontent.com/nGPv7xkoXAZagAvzeSZJR_UFypmsOrSBysDn2XILMcoW6k0e4IOTDw5dn8acI-LJAoR4

**Comment by Timeraa** [comment]
Please open Service requests in the PreMID/Presences repo. Thanks + this is a duplicate so i am going to close this.
