### ISSUE TITLE
Hulu support

### ISSUE THREAD

**Issue by NoNotNick** [PreMiD/PreMiD#181]
I know this isn't an issue, but is there anyway you can add Hulu support?

**Comment by IncognitoJam** [comment]
You should add your request to the [PreMiD/Presences](https://github.com/PreMiD/Presences/issues) repo instead! :)

**Comment by Voknehzyr** [comment]
Hulu are now supported in the new beta.
You can see details here: https://beta.premid.app/store/Hulu
