### ISSUE TITLE
Tab priority bug

### ISSUE THREAD

**Issue by frozaum** [PreMiD/PreMiD#198]
**Describe the bug**
I'm on YouTube, but it says that i'm on RedTube

**To Reproduce**
1. Change to another supported website rapidly
2. Done.

**Expected behavior**
This
![unknown-3](https://cdn.discordapp.com/attachments/526736087377248257/607395681157775361/unknown.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 [Update 1903]
 - Browser: Opera

**Additional context**
I just want to repost this here.

**Comment by Timeraa** [comment]
Fixed in next beta.
