### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by Cairo2k18** [PreMiD/PreMiD#21]
Add linux support (.deb packages and .tar.xz archives).

**Comment by Timeraa** [comment]
Okay, i tried to compile a version, i don't know if it works tho pls try using this version [direct download link](https://github.com/Timeraa/PreMiD/releases/download/v1.2/PreMiD-Linux-amd64.deb)

**Comment by chrisdigity** [comment]
Ubuntu 16.04 LTS
Getting TypeError in the terminal
```
PreMiD: PreMiD - RPC: Could not connect
(node:8550) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at IPCTransport.send (/usr/lib/premid/resources/app.asar/node_modules/discord-rpc/src/transports/IPC.js:151:17)
    at Promise (/usr/lib/premid/resources/app.asar/node_modules/discord-rpc/src/Client.js:152:22)
    at new Promise (<anonymous>)
    at RPCClient.request (/usr/lib/premid/resources/app.asar/node_modules/discord-rpc/src/Client.js:150:12)
    at RPCClient.setActivity (/usr/lib/premid/resources/app.asar/node_modules/discord-rpc/src/Client.js:515:17)
    at Socket.updatePresence (/usr/lib/premid/resources/app.asar/presenceHandler.js:71:24)
    at Socket.emit (events.js:182:13)
    at /usr/lib/premid/resources/app.asar/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:8550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
```

**Comment by Timeraa** [comment]
Hm, ill try my best to fix it. I am not a Linux user so i am not developing on Linux :L

**Comment by Leeo97one** [comment]
I'm on Arch Linux and it works for me!
Here are the steps:
```
git clone https://github.com/Timeraa/PreMiD.git
cd PreMiD/src
npm install
npm start
```
I'll try to make an [AUR](https://aur.archlinux.org/) package someday.

**Comment by Cairo2k18** [comment]
woops didn't notice this till now, i'll try test

**Comment by chrisdigity** [comment]
Same result on Ubuntu 16.04 after following @Leeo97one 's steps :disappointed:

**Comment by chrisdigity** [comment]
OMG this whole time... probably the only thing I didn't try :confused: 
thanks @Voknehzyr 
Disregard my previous messages

**Comment by Timeraa** [comment]
> Make sure that neither intellij or discord are installed through snap (software center).

So i guess thats the problem like MinnDevelopment described?

**Comment by chrisdigity** [comment]
Yeah, reinstalled Discord without snap and now your initial debian package works :+1:

**Comment by Timeraa** [comment]
I'll close this issue, instructions for Linux will be added into the Readme.md

**Comment by CristhianEcheverry** [comment]
The application can not be installed in Ubuntu 19.04, the dependency libgconf-2-4 is required, despite being installed.

**Comment by Cairo2k18** [comment]
There are no longer instructions on how to install or even an official way..?

**Comment by Timeraa** [comment]
I am currently recoding the way releases are being built, when I am done we should be able to support Linux officially. I am not sure but I think we have some docs on how to install it on https://docs.premid.app

**Comment by Cairo2k18** [comment]
> I am currently recoding the way releases are being built, when I am done we should be able to support Linux officially. I am not sure but I think we have some docs on how to install it on https://docs.premid.app

I joined the discord server and saw in the pins a way to install PreMiD, it's not amazing so I can't wait for official support!

**Comment by doomlerd** [comment]
@Cairo2k18 I need some help with testing, are you available nowadays?

**Comment by PoorPocketsMcNewHold** [comment]
I suppose the linked https://aur.archlinux.org/pkgbase/premid/ AUR package is not official then ? Despite working a couple of weeks ago, the URL allowing you to download the compiled .pkg package is down. I´ve marked it as outdated while waiting for an update.
The second premid-git AUR https://aur.archlinux.org/packages/premid-git/ seems to follow the same ways of installation, than the one liner bash installer that we can found on https://docs.premid.app/en/install/linux. However, as already reported on the AUR, both are unable to be installed due to an issue with `npm run pkglinux` (It can´t found the pkglinux module).

**Comment by Cairo2k18** [comment]
> 
> 
> @Cairo2k18 I need some help with testing, are you available nowadays?

Yes, I know a very late response, I am available to help test if you need. (If you need to contact me quickly add me on discord Cairo#1123)

**Comment by doomlerd** [comment]
@PoorPocketsMcNewHold I'm the maintainer of the package, I'm aware it is not working and is not supposed to ( at the moment ), this is the official release : 
https://github.com/doomlerd/PreMiD-Linux 
@Cairo2k18 Sent, DM me.

**Comment by doomlerd** [comment]
For future readers, .deb and .rpm packages will be added tomorrow to the Linux repo.
