### ISSUE TITLE
Wrong episode number on crunchyroll presence

### ISSUE THREAD

**Issue by ksprwhite** [PreMiD/PreMiD#218]
**Describe the bug**
Discord presence show season number instead of episode number on crunchyroll presence on animes of several seasons.

**To Reproduce**
1. go to crunchyroll website
2. watch any anime episode with multiple seasons
3. look at discord presence

**Expected behavior**
show correct episode number

**Desktop:**
 - OS: windows 10 x64
 - Browser: Chrome (77.0.3865.75)

**Additional context**
check PR #217

**Comment by frozaum** [comment]
Hey ksprwhite, the next (stable) version of PreMiD will be a complete rewrite with new stuff (Presence Store which the community can added their Presences and moving to Typescript) even though i'm not a developer, i think this is not going to merged, but thanks for fixing the Crunchyroll issue.
