### ISSUE TITLE
Change to "Watching" & Show Title Image

### ISSUE THREAD

**Issue by Chipx0** [PreMiD/PreMiD#219]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When watching videos Youtube/Netflix, Change the RPC To Watching from Playing. When clicking on a user in Discord, Change the N to the cover art of the current movie/show that you are watching from Netflix

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by paz** [comment]
this is impossible without breaking ToS

**Comment by Timeraa** [comment]
Not possible with the Discord RPC Library in a ToS friendly way
