### ISSUE TITLE
Error when installing from AUR

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [PreMiD/PreMiD#223]
I use `yay -S premid-git` command to install. When installing, I get the following message: `npm ERR! missing script: pkglinux` and installation cancels.
I have installed `nodejs` package.

**Comment by Timeraa** [comment]
I am not officially supporting linux systems so i will put this as help needed.

**Comment by Tohur-Xbl** [comment]
Its because the pkg command was simplified and if you are using pamac or whatever you need to edit the build file and  change npm run pkglinux to npm run pkg. if I can remember my login info to the AUR I will eventually upload an updated PKGBUILD.

**Comment by Tohur-Xbl** [comment]
well that still leaves things borked gona have to refresh myself on PKGBUILD and see if I can get a working one

**Comment by JohnTheCoolingFan** [comment]
When changing `npm run pkglinux` to `npm run pkg`, npm throws an error:
```
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '/home/jtcf/.cache/yay/premid-git/src/PreMiD/pkg'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Also, there are some warn and info messages, that may be interesting too:
```
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
warning " > discord-rpc@3.1.0" has unmet peer dependency "register-scheme@github:devsnek/node-register-scheme".
```

**Comment by TohurTV** [comment]
@JohnTheCoolingFan working on making my own AUR package based on the current install instructions on the Premid website. its the holidays so may be after the first before I get it posted and plus knocking some rust off as been few years since I maintained any packages on any Linux distro haha

**Comment by wallis6n** [comment]
I made a new AUR package https://aur.archlinux.org/packages/premid

**Comment by Timeraa** [comment]
Going to close this as it should be solved by this ^
