### ISSUE TITLE
Updater fails with invalid XML

### ISSUE THREAD

**Issue by Flixbox** [PreMiD/PreMiD#229]
**Describe the bug**
The auto-update just yields a generic error box:

`Command failed: "C:\Program Files (x86)\PreMiD\updater.exe" --mode unattended --unattendedmodebehavior download`

Executing the installer manually yields the following error message:

![image](https://user-images.githubusercontent.com/14835021/66266680-77ef0600-e828-11e9-8a53-f9fe00fff4e4.png)

**To Reproduce**
1. Use the updater, either manually or unattended

**Expected behavior**
The software updates silently (or manually)

**Desktop:**
 - OS: Windows 10 Educational Edition
 - Version 2.0.3

**Comment by Timeraa** [comment]
Probable caused during the api outage, where CloudFlare kicked in with their error message which showed a html page with an error instead of XML
