### ISSUE TITLE
Failed to execute command.

### ISSUE THREAD

**Issue by reithegoat** [PreMiD/PreMiD#231]
**Describe the bug**
Shows an error message about failing to execute a command.

**To Reproduce**
1. Press the "New Update" button in the context menu

**Expected behavior**
For it to find an update and either does nothing or download the new update.

**Screenshots**
![image](https://user-images.githubusercontent.com/11689362/66267566-524e0680-e800-11e9-9a7b-a36d3bf6c965.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Canary (Chromium)
 - Version: Unsure

**Comment by JamesHawkinss** [comment]
Can reproduce.

OS: Windows 10
Browser: Google Chrome
PreMiD Version: 2.0
Chrome Version: 77.0.3865.90

**Comment by RicardoMartens** [comment]
Can reproduce

OS: Windows 10
Browser: Google Chrome
PreMiD Version 2.0
Chrome Version: 77.

**Comment by Timeraa** [comment]
#229
