### ISSUE TITLE
Adding back the ability to disable media key control - PreMiD v2.0

### ISSUE THREAD

**Issue by SgtBreadStick** [PreMiD/PreMiD#232]
**Is your feature request related to a problem? Please describe.**
Having other apps with media key control such as VLC or Spotify no longer work with media keys when you open a youtube video or something even after you close it

**Describe the solution you'd like**
So the solution would be to re-add the option to disable media key control in previous PreMiD versions, as that option is now missing unfortunately.

**Comment by Timeraa** [comment]
Well, it was supposed to be disabled completely for now but it seems i forgot to disable that it binds to the events...
