### ISSUE TITLE
Dialog Option to decide install folder

### ISSUE THREAD

**Issue by Davoleo** [PreMiD/PreMiD#234]
**Is your feature request related to a problem? Please describe.**
It's frustrating when desktop application don't give you the option to decide and they just install in the main C:\ drive that some people may want to keep clean
For example in my case, I have a 250GB SSD drive as my main OS drive and I store all Programs and Other files on my D:\ drive which is an HDD of about 3TB

**Describe the solution you'd like**
A simple dialogue box while installing PreMiD desktop app that allows you to specify a destination directory for the app installation

**Comment by Timeraa** [comment]
I will enhance the installer in the future. Right now i am working really hard to get everything as smooth as possible, automate annoying stuff like building for each os (see GitHub actions) and so on. When i finished all of that i will probably convert the installer to a regular installer.

**Comment by Timeraa** [comment]
Added in the new installer, will soon be on the website.

**Comment by Timeraa** [comment]
Added and released.

**Comment by Davoleo** [comment]
thanks! 
what about #235 ?
is it something you can work on?
