### ISSUE TITLE
PreMiD for Opera and OperaGX platforms.

### ISSUE THREAD

**Issue by Script4Life** [PreMiD/PreMiD#240]
**Is your feature request related to a problem? Please describe.**
Doesn't seem to function on Opera Platforms.

**Describe the solution you'd like**
Possibly make a version of PreMiD that can be compatible with these platforms.

**Describe alternatives you've considered**
Not really.

**Additional context**
If PreMiD is already compatible with Opera platforms, please send a setup Tutorial if possible.

**Comment by Davoleo** [comment]
Yes, you can already install it on Opera, since it's a Chromium based browser

Just install [this extension](https://addons.opera.com/it/extensions/details/install-chrome-extensions/) and then install Premid from the chrome webstore

**Comment by Timeraa** [comment]
Closing this as answered, we won't put it on the opera store as they never reply.
