### ISSUE TITLE
Launch when Discord does

### ISSUE THREAD

**Issue by MegaAura** [PreMiD/PreMiD#243]
**Is your feature request related to a problem? Please describe.**
It's pretty annoying that when I start my pc and login, a few moments later the command prompt loads up asking me for permission. Especially when I don't know what it's asking permission for...

**Describe the solution you'd like**
Having the option to launch PreMid when *Discord* opens. I don't think that I could elaborate on this in more detail.

**Describe alternatives you've considered**
Having another option for when Chrome opens or when the extension connects could be an option too.

**Additional context**
This would be controlled via the extension.

**Comment by Timeraa** [comment]
Normally it should not ask for a command prompt, only if there's an update for PreMiD. Also your idea is nice but not possible

**Comment by MegaAura** [comment]
Oh okay. How were Alpha Console able to attach to Rocket League then? Maybe
if you ask them, you may be able to do something similar.
