### ISSUE TITLE
Linux installer not working

### ISSUE THREAD

**Issue by f1nniboy** [PreMiD/PreMiD#249]
**Describe the bug**
I cannot install the Linux version of PreMiD because it says I am missing a script called **pkglinux**. I searched in the internet but found nothing. I know your priorities are not Linux and will never be but I just want to run your application. Thanks!

**To Reproduce**
1. Go to the Documentation page. ([This site](https://docs.premid.app/en/install/linux))
2. Copy the command for **Other distributions*
3. Choose the first option and run the command in a terminal (use the git console on Windows or run on Linux).

**Expected behavior**

> ..., wait for it to install, double-click the "PreMiD" shortcut created on your Desktop, and that's it!

**Screenshots**
![image](https://user-images.githubusercontent.com/55994155/67037748-6b1ebc00-f11e-11e9-80b4-f559f0093ceb.png)

**Desktop (please complete the following information):**
 - OS: elementary OS (based on Ubuntu Ubuntu 18.04.2 LTS)
 - Browser: Chromium
 - Version of Browser: 77.0.3865.90 (official build)

**Additional context**
None. If asked I will provide more information.

**Comment by f1nniboy** [comment]
I joined the server and got an answer.

**Comment by superloach** [comment]
Would you mind sharing your solution? I had the same issue, and it seems that #223 is the same.

**Comment by f1nniboy** [comment]
Its in the Discord server. 
Text from the server:

> :tada: PreMiD 2.0.1 for Linux ( another AppImage ) :
> https://doomlord.s-ul.eu/QADcNaqP
> 
> Run chmod +x ./PreMiD*.AppImage in the download directory (or where it's located) then open it (double click).
