### ISSUE TITLE
Masterani.me

### ISSUE THREAD

**Issue by Jaydan69** [PreMiD/PreMiD#26]
**What's the name of the service?**
https://www.masterani.me/

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
It is used by a lot of people and when people ask what anime you are watching it will show on your discord profile instead. This site also has a discord with over 1000(currently online when i checked) or so members, It would be cool to stunt their service on discord. (also promote this app abit which is pretty cool).

**Are you able to provide an image for the service? (512x512 minimum)**
![masteranime](https://user-images.githubusercontent.com/20286530/48763534-98da6580-ed01-11e8-861c-4d5cb3a53e95.png)
Sorry, I tried getting the best image i could.

**Comment by Timeraa** [comment]
Thanks, i will take a look at **Masterani.me**.

**Comment by Numpftakeaname** [comment]
Good Site

**Comment by Fruxh** [comment]
Masterani.me is now closed
