### ISSUE TITLE
Extension doesn't recognize client

### ISSUE THREAD

**Issue by jclgc** [PreMiD/PreMiD#260]
**Describe the bug**
I have the PreMiD application up and running, it's in my status bar, and i have the extension installed - but the extension says "Not connected," meaning it thinks I don't have the application (properly) installed

**To Reproduce**
1. Install the PreMiD application
2. Install the PreMiD browser extension

**Expected behavior**
I expect PreMiD to be functional at this point

**Screenshots**
https://i.imgur.com/EGmtovV.png

**Desktop (please complete the following information):**
 - OS: MacOS Sierra 10.12.6
 - Browser: Chrome
 - Version 2.0.1.3

**Additional context**
I tried accessing the troubleshooting page, and since it seems to be down for an undefined amount of time, I made an issue here.

**Comment by frozaum** [comment]
can you try the wiki now?

**Comment by Timeraa** [comment]
Going to close this, if this issue persists, https://discord.gg/PreMiD #support
