### ISSUE TITLE
Support for Opera.

### ISSUE THREAD

**Issue by eiruu** [PreMiD/PreMiD#285]

**Comment by Bas950** [comment]
We support opera, 
Download the extension "Install chrome extensions" in opera
https://addons.opera.com/nl/extensions/details/install-chrome-extensions/
and then install our chromium extension.

**Comment by eiruu** [comment]
Yeah that doesn't work. It's not displaying in Discord anything.

**Comment by Bas950** [comment]
Please contact us in our discord to get support. discord.gg/premid

**Comment by eiruu** [comment]
Oh sorry, it does. I didn't notice that. Thanks a lot.
