### ISSUE TITLE
Premid Schedule Bug

### ISSUE THREAD

**Issue by Arion-Kun** [PreMiD/PreMiD#322]
**Describe the bug**
After a while with a fullscreen application or a focused application for a second or two the application fails to focus as Premid is directing focus from the current application.
Observed Behavior: Fullscreened videos shows the windows task bar for a second after watching for some time, I suspect this is some sort of scheduled update check for premid where it doesnt hide it due to some sort of priority. This also happens during games such as League of Legends where application focus loss sends the game to 18 fps until refocused.

**To Reproduce**
1. Watch a video or play a game for some time (or afk in a fullscreen application)
2. Wait for premid to do potential update check
3. Windows Taskbar briefly shows up during games causing a loss of focus on the current application

**Expected behavior**
Loss of focus does not occur.

**Desktop (please complete the following information):**
 - OS: Windows OS (Windows 10 Up to Date)
 - Browser Chrome

**Additional context**
Please reply to request additional contextual information if need be.

**Comment by Timeraa** [comment]
Hm, Idk if I can do something about that with the update checker I am using so I may need to do my own small solution, will see what I can do

**Comment by tepiloxtl** [comment]
Commenting here on request from fror#9493: I have symptoms mentioned in issue, its due to updater.exe from PreMid installation directory running periodically in foreground, and stealing focus from whatever process is in foreground now. Video proof https://www.youtube.com/watch?v=GWzRFL7BMHc

**Comment by Timeraa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Recode Updater](https://trello.com/c/Z6xNNQCm/65-recode-updater)
