### ISSUE TITLE
Premid script

### ISSUE THREAD

**Issue by yagiyomichi** [PreMiD/PreMiD#327]
Please, create a PreMiD version for userscripts.
I'm a user of a web browser with Qt motor engine, usually I can found extensions with script compatibility in greasyfork and use this in Violentmonkey,, but was a unexpected surprise that PreMiD still dont have this option....
Please make this happen!

**Comment by tooruu** [comment]
use a regular browser?

**Comment by Timeraa** [comment]
Don't understand what it is and why. Most likely not being able to be supported.
