### ISSUE TITLE
Presence shop/editor

### ISSUE THREAD

**Issue by Fruxh** [PreMiD/PreMiD#35]
**Is your feature request related to a problem? Please describe.**
Eww, problems...

**Describe the solution you'd like**
It would be awesome to add your sites by yourself with something like an editor for example!

**Describe alternatives you've considered**
Make a presence shop :3

**Additional context**
Here's a cute kitten :3
![image](https://user-images.githubusercontent.com/37774297/49184228-20a61c80-f35f-11e8-8301-1c37f0d06b4f.png)

**Comment by SupaSickWog** [comment]
This would be cool

**Comment by Timeraa** [comment]
*Not like this is included in V2.0 🤔*

**Comment by xPazz** [comment]
isnt this done now @Fruxh @Timeraa
