### ISSUE TITLE
windows premid unable to install update or going to a loop

### ISSUE THREAD

**Issue by RootAndroid58** [PreMiD/PreMiD#352]
**issue:**
idk why but premid installed itself 35 times by now and its in the same loop plz check that out it says 
Type error cannot read property of message of null in src\updatechecker.ts 74:12
child process exit handler 299:7
child process emmit 203:13
maybeclose childprocess.js1021:16
scoket anynomus 430:11
and few more lines

**Describe the solution you'd like**
simply click on check for updates and if available download else up to  date message without any loops XD

**Additional context**
no

**Comment by destr0yed** [comment]
I got the same issue and uploaded a video. 
Sometimes the updater kinda 'forgets' to kill the main process right in time which leads to an R/W error when it is trying to replace the executable. 
[https://youtu.be/pZUqSgGQNzA](https://youtu.be/pZUqSgGQNzA)

**Comment by episcia** [comment]
Also encountering this issue. The error message in the OP is slightly incorrect, see this screenshot

![image](https://user-images.githubusercontent.com/60572143/73608287-858f7f00-45c1-11ea-934e-024df73c4429.png)

**Comment by RicardoMartens** [comment]
> Also encountering this issue. The error message in the OP is slightly incorrect, see this screenshot
> 
> ![image](https://user-images.githubusercontent.com/60572143/73608287-858f7f00-45c1-11ea-934e-024df73c4429.png)

Experiencing this as well, +1

**Comment by RadegasTCZ** [comment]
![vlcsnap-2020-02-02-20h19m43s868](https://user-images.githubusercontent.com/22341950/73613797-7cba9f80-45f9-11ea-95d7-436eda9a6020.jpg)

Mine even started and crashed multiple ones.

**Comment by ErdbeerbaerLP** [comment]
Any way of disabling that update stuff. It is annoying to see an message every 10 minutes or so telling me to do an impossible update

**Comment by RadegasTCZ** [comment]
> Any way of disabling that update stuff. It is annoying to see an message every 10 minutes or so telling me to do an impossible update. I could block the whole premid domain in my pi-hole

For that just wait until notification pops out. Then right click on it and turn of all notifications for xxxxxxx"appname"

**Comment by Alanexei** [comment]
All of the issues reported here are common with the updater. Timeraa will be working on this.

**Comment by Timeraa** [comment]
Hi, first of all sorry that that stuff happened in the first place, nobody is perfect I guess.

To fix this try to completely close PreMiD with its upgraders, then try to uninstall it if it leaves some files, delete them. Then download the installer again from the [website](https://premid.app/downloads) and then it should work.

**Comment by RadegasTCZ** [comment]
> Hi, first of all sorry that that stuff happened in the first place, nobody is perfect I guess.
> 
> To fix this try to completely close PreMiD with its upgraders, then try to uninstall it if it leaves some files, delete them. Then download the installer again from the [website](https://premid.app/downloads) and then it should work.

OK I will try in when I will be on my laptop, where should I expect some files to be removed other than %programfiles% and maybe temp files?

**Comment by ErdbeerbaerLP** [comment]
Uninstall.exe can not be found. Gonna manually delete the whole folder

**Comment by RadegasTCZ** [comment]
Reinstalled with newest version manually. Worked fine, now... Is it supposed to show something when no update is avaiable?

**Comment by NotNite** [comment]
The fact that there's no uninstaller is kind of weird.

**Comment by NotNite** [comment]
Cool, fixed, but why isn't the issue closed?

**Comment by RadegasTCZ** [comment]
I have no idea.
