### ISSUE TITLE
Unable to update PreMiD on mac

### ISSUE THREAD

**Issue by cleverActon0126** [PreMiD/PreMiD#366]
**Describe the bug**
After pressing update PreMiD, it still won't update even I restarted my mac

**To Reproduce**
Steps to reproduce the behaviour:
1. press the extension and press update(but it wouldn't)

**Expected behaviour**
Should update the app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 2.1.1

**Additional context**

**Comment by RadegasTCZ** [comment]
Yeah similar problem on my windows PC, had to force it to run as administrator, hopefully it has been fixed in 2.1.3

**Comment by cleverActon0126** [comment]
thanks
Acton C.
