### ISSUE TITLE
Problems with firefox

### ISSUE THREAD

**Issue by Andrey-ui** [PreMiD/PreMiD#379]
**Describe the bug**
Firefox addons cannot can be instaled

**Desktop (please complete the following information):**
 - OS: [Win 10 Pro]
 - Browser [Firefox]
 - Version [2.1.2]

**Comment by frozaum** [comment]
Hello @Slasar41, Can you join our [Discord server](https://discord.gg/WvfVZ8T) and create a ticket on #support?

Thanks.

(closed)
