### ISSUE TITLE
Does not work with the new Microsoft Edge

### ISSUE THREAD

**Issue by Slasar41** [PreMiD/PreMiD#380]
**Describe the bug**
Using PreMID (with it's extension) on Windows 10 does not work with the new Microsoft Edge, it works with Chrome on the same machine.

**To Reproduce**
1. Install the new Microsoft Edge
2. Install premid and the extension from the chrome web store
3. See how the app and extension show as "connected" but you won't see anything on your discord status.

**Expected behavior**
Discord show your status while you're watching something supported by premid using the new Microsoft Edge.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 x64
 - Browser: Microsoft Edge Stable 80.0.361.57
 - Version: 2.1.2

**Additional context**

**Comment by frozaum** [comment]
Hello @Slasar41, i'm currently using the new Microsoft Edge and having no problems so far
![image](https://user-images.githubusercontent.com/34042085/75379334-f7eb3a80-58b3-11ea-9c26-11a89c84902e.png)

Can you try all of the steps available in our [troubleshooting page](https://docs.premid.app/en/troubleshooting)?
If that didn't work, please join our [Discord server](https://discord.gg/WvfVZ8T) and create a ticket on #support!

(closed)

**Comment by Slasar41** [comment]
Looks like I don't realize there's another Discord app already running before.
It's working fine now. Thanks for the help.
