### ISSUE TITLE
no presence, as if it doesnt see me doing things in the browser.

### ISSUE THREAD

**Issue by Sepsy3** [PreMiD/PreMiD#418]
**Describe the bug**
no presence on discord and on the system menubar
**To Reproduce**
1. run Premid normally
2.???
3. no presence

**Expected behavior**
should show what i am doing in the browser in discord rich presence and system menubar.

**Screenshots**
![image](https://user-images.githubusercontent.com/61350797/78450224-d08f4680-7685-11ea-8ff7-5575b72dce7b.png)
![image](https://user-images.githubusercontent.com/61350797/78450227-d4bb6400-7685-11ea-8df1-1030bbc66953.png)
![image](https://user-images.githubusercontent.com/61350797/78450229-d7b65480-7685-11ea-8473-a151ef952787.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina ver. 10.15.4
 - Browser Chrome
 - Version v.2.1.2

**Additional context**
was working before the failed to update fix.

**Comment by Bas950** [comment]
Please take a look at your troubleshooting page here: https://docs.premid.app/en/troubleshooting
And if that doesnt help you please join our Discord Server for faster support. https://discord.premid.app/
