### ISSUE TITLE
Update fail after PC start up FIX

### ISSUE THREAD

**Issue by RadegasTCZ** [PreMiD/PreMiD#422]
If you experience update fail after your PC has booted up, try starting PreMiD as an administrator and manually try to update again, most likely it forgets to ask for administrator permissions

EDIT: I lost a illustration screenshot of an error you might experience, whatever, successfully updated to 2.1.3 (9.4.2020 @ 11:14)

**Comment by Timeraa** [comment]
Can you try to reinstall PreMiD? Btw the new one doesn't need Administrator permissions as it installs into appdata

**Comment by RadegasTCZ** [comment]
> Can you try to reinstall PreMiD? Btw the new one doesn't need Administrator permissions as it installs into appdata

Well I don't know just yet, but on my desktop I just fixed it by running it as an administrator, then I told it to check for updates and installation went fine. I am gonna se what version I am running on my laptop as soon as I will be able to get to it.
