### ISSUE TITLE
Premid not working for sites i downloaded the rich presence of myself

### ISSUE THREAD

**Issue by khasugha** [PreMiD/PreMiD#438]
**Describe the bug**
After i installed the app and the extension and downloaded a couple of rich presences it works for sites like twitch and youtube that came with it automatically but its not working for the ones i downloaded like bilibili.com

**To Reproduce**
1. download premid
2. download premid extension
3. launch bilibili.com

**Expected behavior**
discord showing me browsing bilibili like it does for youtube

**Screenshots**
https://i.imgur.com/FTSQUqo.jpg
https://i.imgur.com/wAhtAse.jpg

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] newest

**Additional context**
its not only bilibili but all the presences ive downloaded outside the ones included in the application

**Comment by OfficialCRUGG** [comment]
![image](https://user-images.githubusercontent.com/25248999/80354088-8fe6af80-8876-11ea-823d-c34f90915b38.png)
Are you sure the Presence is listed in the PreMiD Extension and is enabled?
