### ISSUE TITLE
Documented API for other applications

### ISSUE THREAD

**Issue by paz** [PreMiD/PreMiD#445]
**Is your feature request related to a problem? Please describe.**
Many applications woud like to use now playing information to develop new features for their app, examples:

Rainmeter(WebNowPlaying): https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli  
Minecraft(MediaMod): https://chrome.google.com/webstore/detail/mediamod/oeocpffgjbagninjebpgopolopdegogb?hl=en  
Other(To text file): https://chrome.google.com/webstore/detail/universal-now-playing-com/lljahlkpnhdopaegadghfjhhkcpdlijg

Many of these solutions only support a few websites, or are broken entirely over time with changes to the sites/apps it supports.

**Describe the solution you'd like**
A documented API to interface PreMiD's extensive support of many websites for Now Playing information. This would allow other apps to access this information without having to install many other extensions to your browser to add the same feature just for different apps. The PreMiD desktop application could also support outputing to a text file to universally support older legacy applications, however this could also be seperated into another application for this function.

**Describe alternatives you've considered**
The API exists, somewhat, but it's not documented and many developers who would want this functionality would never find it.

**Comment by OfficialCRUGG** [comment]
Yes! That's a super amazing Idea. So basically PreMiD would open up a Webserver with the Info about the current Playing Status? So like http://127.0.0.1:1234/info would return something like
```
{
   "presence": {
        "name": "YouTube Music",
        "category": "music"
    },
   "details": "something",
   "state": "something"
}
```
Is that what you mean? If yes, it would probably be also cool if a Presence could set custom Values (e.g. Artist and Album separated) which would be stored in some Object maybe?
But yes this would be very very useful. Saving to a .txt File as an Option would be very useful as well. So you could for example show the currently playing Song on YouTube Music in Streams. But yeah even the JSON API would be pretty cool for stuff like Rainmeter Widgets.
Maybe add a Settings Window where you can enable/disable those things? Should also be disabled by default in my opinion since not that many people would use e.g. the Web API for example and a Webserver kinda takes some resources.

**Comment by paz** [comment]
yes

**Comment by paz** [comment]
currently the premid app is a web server listening for the premid extension's requests (posts information), so the premid app would host the API

**Comment by PhantomNimbi** [comment]
This would be extremely useful for webapps build through nativefier since they don't have support for extensions. I definitely would like to see this one implemented if possible.

**Comment by OfficialCRUGG** [comment]
> This would be extremely useful for webapps build through nativefier since they don't have support for extensions. I definitely would like to see this one implemented if possible.

Just for your Information, this is about a local API to GET the current Presence to use that Information in an Application like e.g. a Rainmeter Widget. This is **not** about using a local API to POST a Presence, however that would be a possibility too. @PhantomNimbi

**Comment by paz** [comment]
> > This would be extremely useful for webapps build through nativefier since they don't have support for extensions. I definitely would like to see this one implemented if possible.
> 
> Just for your Information, this is about a local API to GET the current Presence to use that Information in an Application like e.g. a Rainmeter Widget. This is **not** about using a local API to POST a Presence, however that would be a possibility too. @PhantomNimbi

you should be able to do both pretty easily if you do one of them

**Comment by kawakami** [comment]
Added to To-Do list for v3. Thanks for suggestion. Probably it will not be on v3 release but later :wink:

**Comment by paz** [comment]
^ a post api would make desktop apps like Adobe rich presence possible. Requiring an API key will make that more secure

**Comment by kawakami** [comment]
We will think about implementing POST API to app. For now I will add it as suggestion.

**Comment by paz** [comment]
also wanna mention it should be only locally accessible, obviously :p

**Comment by kawakami** [comment]
You didnt had to say that, I know it.

**Comment by paz** [comment]
The socketio api wasnt closed in v2, thats why I mentioned it

**Comment by Timeraa** [comment]
I think there's no need for this anymore since the app is not needed anymore to use it.
