### ISSUE TITLE
Unrecognized Manifest Key 'Applications' Error - PreMiD Chrome Extension

### ISSUE THREAD

**Issue by PhantomNimbi** [PreMiD/PreMiD#498]
**Describe the bug**
The presence is not working in Chrome based browsers. There is an error in the log saying `Unrecognized Manifest Key 'Applications'`  that shows the following key:

```
"applications": {
      "gecko": {
         "id": "support@premid.app",
         "strict_min_version": "52.0",
         "update_url": "https://api.premid.app/firefox/updates"
      }
   },
```

Pretty sure chrome doesn't use firefox update channels...

**To Reproduce**
Download Any Chrome based browser.
Install and setup the PreMiD extension from the chrome web store.
Open Discord [make sure the browser is detectable].
Try to view one of the websites of which you have the presence for.

**Expected behavior**
Should show the status properly

**Screenshots**
![PreMiD Error](https://user-images.githubusercontent.com/17615050/86362904-d7990700-bc2a-11ea-9be6-ef80dd3c0740.png)
![PreMiD Status Error](https://user-images.githubusercontent.com/17615050/86362910-dcf65180-bc2a-11ea-9e74-dbc752a7edf1.png)

**Desktop:**
 - OS: Windows 10 20H1
 - Browser Vivaldi [Chrome based]
 - Version 3.2.1964.3 (Official Build) (64-bit)

**Comment by kawakaami** [comment]
Should work even with that. Next time use https://github.com/PreMiD/Extension repo. To close.

**Comment by Timeraa** [comment]
Its just a compatibility layer for Firefox extensions, its only a warning and won't cause any issues.
