### ISSUE TITLE
firefox extension installs on macos but not on windows

### ISSUE THREAD

**Issue by gloubix** [PreMiD/PreMiD#522]
![error](https://user-images.githubusercontent.com/1148460/87876007-4ae59b80-c9d5-11ea-96da-42198b99a175.jpg)

Hi, i have this error when tring to install extension on firefox.
It's french but it says that there is a network problem....

firefox nightly : 80.0a1 : same as my Macbook pro for firefox but the extension install and work on macos but not on windows.

Is there a way to get an xpi file to install it manualy ?

THX

**Comment by kawakaami** [comment]
https://dl.premid.app/PreMiD.xpi

**Comment by AlanReviews** [comment]
I never received that problem on my stable Firefox browser and nightly. I cannot comment on beta and developer edition.

**Comment by gloubix** [comment]
working thx
