### ISSUE TITLE
Doesn't work with YouTube's non-polymer interface 

### ISSUE THREAD

**Issue by LothaireCliquennois** [PreMiD/PreMiD#533]
**Describe the bug**
When using the older YouTube interface (still used by some people because of either old browser, or just not wanting to use the broken interface), the video you're listening isn't shown on Discord.

**To Reproduce**
1. Using the old YouTube interface while being either on an older version of the browser, or just using Good Old youtube extension on Chromium based browsers or Firefox
2. Loading whichever video comes first, the video choice does not seem to matter.
3. Checking on Discord the status you have as a user.

**Expected behavior**

Seeing the video I'm playing on Discord, as it does the second you switch to the polymer interface...
**Screenshots**
![image](https://user-images.githubusercontent.com/41753021/89562331-1ae22900-d81a-11ea-90e4-7567a69f13d8.png)
![image](https://user-images.githubusercontent.com/41753021/89563223-6943f780-d81b-11ea-9705-7a2e2b04b755.png)

**Desktop:**
 - OS: As I've tested on Windows 7, 8.1, and Linux, I may say it happens everywhere you're using the older interface.
 - Browser : tested on Chromium, Google Chrome, Firefox, and Edge Chromium.
 - Version : latest versions of the browsers, and it doesn't seem to make a difference.

**Comment by fr0r** [comment]
no.
