### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by EstevaoU** [PreMiD/PreMiD#563]
**PreMiD doesn't work**
I did everything it needs but nothing happens to my discord status

**To Reproduce**
1. Install the application and chrome extension
2. Start both
3. Open youtube
4. ₊˚✧ . ˚Nothing happens ˚✧ . ˚

**Expected behavior**
It should work... right?

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 85.0.4183.121

**Additional context**
I already tried using firefox, and i think that the problem isn't with the PreMiD itself but with the Discord app. I have literally no idea of what to do

**Comment by Bas950** [comment]
Feel free to contact us in our discord (https://discord.premid.app/)
You can make a ticket in the #support channel
