### ISSUE TITLE
Error Box on Every Windows Startup

### ISSUE THREAD

**Issue by AlperSal** [PreMiD/PreMiD#564]
**Describe the bug**
An error box after every Windows startup. (Screenshot added)

**To Reproduce**
Steps to reproduce the behavior: (I don't exactly know what does reproduce means but I think it is how to make bug happen)
1. Just reboot/start the computer.

**Expected behavior**
I expect PreMiD runs on startup without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34231577/94337345-6fbc4780-fff2-11ea-9dec-c2b612ee26ba.png)

**Desktop (please complete the following information):**
 - OS: Windpws
 - Browser: Chrome
 - Version: v2.1.3

**Additional context**
PreMiD is already running when error box pops-up.
Sorry for my bad English.

**Comment by Bas950** [comment]
It already auto-launches on startup so you don't have to start it yourself, this error means that it is already running.

If you still got further issues, feel free to make a ticket in our Discord (https://discord.premid.app/)
