### ISSUE TITLE
[bug] Troubleshooting link is broken

### ISSUE THREAD

**Issue by HQv2** [PreMiD/PreMiD#623]
A small bug to report. When you don't have the pc app installed, the troubleshooting link is broken. 
<img width="221" alt="Screenshot_5" src="https://user-images.githubusercontent.com/42633588/102045810-f4279680-3da7-11eb-9d4b-d1fbd514bf1f.png">

Links to this page: https://docs.premid.app/en-US/troubleshooting

**Comment by ririxidev** [comment]
Already fixed in beta version
