### ISSUE TITLE
soundcloud not working

### ISSUE THREAD

**Issue by toesss23** [PreMiD/PreMiD#625]
**Describe the bug**
Not sure if i can make this super clear but the soundcloud presence is not showing up. 
**To Reproduce**
1.download premid a bunch of times
2.download extension after those bunch of times
3. download soundcloud on the store of premid, delete it, then redownload it on the store.(did this cus it wasnt working and still isnt)
4. 

**Expected behavior**
i expected the presence to work correctly 

**Screenshots**
https://gyazo.com/31555854813f04a931a1621732013370
https://gyazo.com/09f338a29085d6fcc5c9633c71e6c0dd
**Desktop (please complete the following information):**
 - OS: windows 10 home
 - Browser chrome
 - Version 2.1.4
**Additional context**
i have a custom google chrome thing where i can name it playing what ever i want so maybe that has something to do with it but i deleted it already and it isnt working. also youtube music and normal youtube works but soundcloud doesnt

**Comment by toesss23** [comment]
also have betterdiscord if that might effect it

**Comment by Timeraa** [comment]
Please open Presence related bugs on the [Presences](https://github.com/PreMiD/Presences/issues) repo. But these Presences should work as they are the main ones.

But yes BetterDiscord likes break PreMiD by uninstalling the discord RPC server that's installed with Discord.
