### ISSUE TITLE
Premid does not display Youtube, but other sites work just fine.

### ISSUE THREAD

**Issue by Jeggie-Ex** [PreMiD/PreMiD#630]
**Describe the bug**
Premid only have issues when trying to display youtube. Other sites tested, and they all work fine. (Youtube Music, Mangadex, and Custom Status work with no issues.)

**To Reproduce**
1. Install Premid
2. Install the Youtube Presence
3. Open www.youtube.com
4. Check your discord status
5. It shows nothing.

**Expected behavior**
Premid will display on discord what youtube video am i watching, the uploader, and duration left.

**Desktop (please complete the following information):**
 - OS: Windows 10 version 2004 build 19041.685
 - Browser: Opera GX version LVL 2 (core: 72.0.3815.459)

**Additional context**
It used to work flawlessly. Also, i am used to toggle the youtube presence quite often, if that actually affects it. Already tried reinstalling both the extension and the application.

**Comment by rurunruna** [comment]
Same Issue as mine.. It worked like last 4-5 days ago.. I tried the same method as you did too, and It did not work.

**Comment by Timeraa** [comment]
Please open Presence related bugs on the [Presences](https://github.com/PreMiD/Presences/issues) repo. But these Presences should work as they are the main ones.
