### ISSUE TITLE
Add the possibility to disable tray icon

### ISSUE THREAD

**Issue by cwrau** [PreMiD/PreMiD#641]
**Is your feature request related to a problem? Please describe.**
I don't need a tray icon, it just clutters my tray area

**Describe the solution you'd like**
A command flag to disable the tray icon, maybe `--no-tray-icon`

**Describe alternatives you've considered**
A config file in which I can disable the tray icon, though that'd be less desirable for me

**Additional context**

**Comment by Timeraa** [comment]
Closing in favor of #645
