### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by Macleykun** [PreMiD/PreMiD#645]
Premid has a tray icon to:
1. show version
2. is it connected to the plugin
3. quick link to presence store (also present in the extension)
4. Check for updates
5. Achnowledgements
6. Quit remid

I would suggest if we can move these options to the extension, so that a tray icon is not needed anymore. I know this is a very niech thing to ask but personally i don't have to see premid as a tray icon if possible. As i think the above functionalities can be done from the plugin options itself.

Alternatively, i would suggest having the option to hide the Premid tray icon. Maybe this can be toggeld on again from the extension or by running the program manually again (not when it's autostarted)

Again i know this is a very small suggestion, but i wanted to ask what the devs/others think of this. I tottaly understand if this feature get's closed because it wouldn't make much sense.

**Comment by Macleykun** [comment]
Pardon for the incorrect feature post, stupid of me to not place it in the correct repo of the *app* 🤦
Sounds perfect! Thank you :) looking forward and have a great day!

**Comment by Timeraa** [comment]
Will be added in v3 *if it will have a tray at all*

**Comment by Macleykun** [comment]
Sure thing! Really looking forward to it! Hope your doing well in life :)

**Comment by Macleykun** [comment]
heya, was wondering how it's going with you, and your project :)

**Comment by Timeraa** [comment]
Good, the project was a bit halted since we were/still are doing a lot of infrastructure changes to prepare for the next updates.

**Comment by Macleykun** [comment]
ooh awsome! do you post these updates somewhere?

**Comment by Timeraa** [comment]
Not really, wanted to post them regularly on Patreon but well, I always forget

**Comment by Macleykun** [comment]
understandable :P but it's awsome ya still working on it!

**Comment by Macleykun** [comment]
heya dude! how's life and progress :) ?

**Comment by Timeraa** [comment]
Hey, we're working on the next update and as well as the company behind it at rn

**Comment by Macleykun** [comment]
Eyy good to hear :) <3

**Comment by Macleykun** [comment]
heya Tim, it's been a while :) how are things going in life and with the project?
