### ISSUE TITLE
Detected as Malware

### ISSUE THREAD

**Issue by hwalker928** [PreMiD/PreMiD#647]
**Describe the bug**
VirusTotal classifies this as a RAT and a svchost malware. Check relations and community tab.

**To Reproduce**
1. Download the file
2. Upload to VirusTotal.com
3. Click relations and community.
4. https://www.virustotal.com/gui/file/8244204c1226a24d2842412ce429a09659ab66bcd7c4cb4f072a786b878ecbc4/detection

**Expected behavior**
No malware.

**Screenshots**
https://ss.harrydev.me/i/uqhv9egv5c.png
https://ss.harrydev.me/i/8mts1wep2k.png
https://ss.harrydev.me/i/n51z2lp0b1.png

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Bas950** [comment]
It's a false positive, we are open source as you have noticed since you are reporting it here, you can even build the app yourself if you want to.
