### ISSUE TITLE
Extremely slow bootup time on MacOS, freezes all other proccesses running

### ISSUE THREAD

**Issue by 150mg** [PreMiD/PreMiD#672]
Restarting Mac device leads to PreMid resetting itself upon startup, causing all other proccesses on the device to freeze. Takes around 20-40 seconds for device to open PreMid again. Can't click, move cursor or force-quit out of PreMid during this. I am positive PreMid is the cause of this but not sure why.

1. Restart Mac device, have PreMid on launch at startup.

**Expected behavior**
Smooth bootup from the device with no lag or freezing. Should be able to move and click the cursor freely.

 Operating on MacOS Mojave 10.14.6

This doesn't happen with my Windows PC with the same launch at startup option ticked so I'm not sure why it's suddenly happening to my Mac one? App is fully updated, even tried a clean uninstall and reinstall.

**Comment by Timeraa** [comment]
That's odd, I can only say that there will be a completely new app soon which hopefully fixes those issues.

**Comment by ririxidev** [comment]
Can't reproduce either.
