### ISSUE TITLE
IHeartRadio does not show the station you are playing. Only shows "browsing..."

### ISSUE THREAD

**Issue by Jorn72** [PreMiD/PreMiD#687]
**Describe the bug**
When I choose a radio station on IHeartRadio, It shows up in Discord. That's working as it should. It does not show the station that you are listening to. It does only show "Browsing..." instead. 

**To Reproduce**
1. Enable the IHeartRadio add-on
2. play a radio station on Iheart.com

**Expected behavior**
It should show the radio station that you are Listening to. "RadioStationName" Instead of "browsing..."

**Screenshots**
![image](https://user-images.githubusercontent.com/61007325/111379413-665b9000-86a3-11eb-8d49-04c7f70f1314.png)

**Desktop:**
 - OS: Windows 10 Home&Pro
 - Browser: Chrome&Firefox
 - Version: 89.0.4389.82(Chrome) 85.0.2 (Firefox) 2.2.0 (PreMID)

**Additional context**
None

**Comment by callumok2004** [comment]
Direct all presence related issies to https://github.com/premid/presences
