### ISSUE TITLE
Youtube not showing as rich presence

### ISSUE THREAD

**Issue by ItMeVaxi** [PreMiD/PreMiD#708]
**Describe the bug**
Youtube not showing in discord Status

**To Reproduce**
1. install premid
2. install youtube extension for premid

**Expected behavior**
Youtube showing up sd discord presence

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser opera gx (tried it on firefox aswell)
 - Version most recent to 4/20/2021

**Additional context**

**Comment by retroretro** [comment]
bump, been having this issue as well. never been a problem in the past. tried switching browsers, reinstalling app and extension. every other presence works perfectly fine. running latest premid version on ubuntu 20.04 with firefox.

**Comment by retroretro** [comment]
this will fix the issue: https://gyazo.com/f067c4725cb122322f239717067a64d9

though i still dont understand why this is happening in the first place, hopefully the devs can look into it.

**Comment by mihaisupport** [comment]
> this will fix the issue: https://gyazo.com/f067c4725cb122322f239717067a64d9
> 
> though i still dont understand why this is happening in the first place, hopefully the devs can look into it.

even if you do that, the problem still occurs... its also happening to me again... youtube, netflix is not showing... but rest of them is showing! (the extensions says that everything is connected, but the extension really sucks >.<)

**Comment by mihaisupport** [comment]
I want also to mention: when you do the steps from this link: https://gyazo.com/f067c4725cb122322f239717067a64d9 that ”Language” thing, is gone forever, so you need to remove the presence and add it again, in order to show... (this is so frustating already)

**Comment by Bas950** [comment]
> I want also to mention: when you do the steps from this link: https://gyazo.com/f067c4725cb122322f239717067a64d9 that ”Language” thing, is gone forever, so you need to remove the presence and add it again, in order to show... (this is so frustating already)

Please make a ticket in #support in our [Discord server](https://discord.premid.app/) so we can help you faster.
