### ISSUE TITLE
premid breaks / lags behind with more then one instance of discord running 

### ISSUE THREAD

**Issue by ProFireDev** [PreMiD/PreMiD#729]
i have canary, Public beta aswell as the production version of discord open constantly, with 2 of them having different accounts, premid has a hard time trying to choose which one to give the presence too.

would it be possible to just make it so it can give both accounts the same presence

**Comment by Timeraa** [comment]
We know of this "issue" but we won't fix this issue anytime soon/ever since normally you only use one instance of Discord at a time and PreMiD just searches for the next available port to use.
