### ISSUE TITLE
discord desktop app issue?

### ISSUE THREAD

**Issue by arianabary** [PreMiD/PreMiD#742]
uh so whenever I open the discord desktop app it always comes up with this Netflix show I haven't watched in weeks and I can't seem to get rid of it help?? :>
![premid issue](https://user-images.githubusercontent.com/60813009/119993357-94ecd400-c01f-11eb-8773-27fe28670a94.PNG)

**Comment by Timeraa** [comment]
Try restarting PreMiD and your browser if that doesn't help reinstall them both
