### ISSUE TITLE
PreMiD will display a previous random status sometimes after waking computer after sleep mode

### ISSUE THREAD

**Issue by unicornbetrayal** [PreMiD/PreMiD#743]
**Describe the bug**
Every once in a while, PreMiD sometimes displays a seemingly random previous status after waking the computer from sleep.

**To Reproduce**

1. Put the computer to sleep with a browser and Discord running (no tabs open that could trigger the rich presence to display a status)
2. Wake the computer up from sleep mode after a couple of hours
3. Every once in a while, a random status that was previously used will display with a couple of hours of time elapsed since the computer was set to sleep mode, despite no website being open.

**Expected behavior**
The PreMiD extension should not display any status as no website is open to trigger the rich presence. 

**Desktop (please complete the following information):**

- OS: Windows 10 Home

- Browser: Google Chrome

- Version: PreMiD v2.2.0

**Comment by Timeraa** [comment]
I know of issues that either Discord sometimes keeps a status showing and that PreMiD sometimes gets stuck with one, we'll try our best to fix these issues in the next updates

**Comment by unicornbetrayal** [comment]
> I know of issues that either Discord sometimes keeps a status showing and that PreMiD sometimes gets stuck with one, we'll try our best to fix these issues in the next updates

Thank you for your response, it is good to know that there are plans on patching this.

**Comment by ririxidev** [comment]
It is most likely discord RPC server that is completely broken and doesn't clear Activity when it has to, it doesn't only happens with PreMiD but with other applications too. About "not cleaning activity" from PreMiD, yes it sometimes happens, but it is rare. It most likely happens from discord RPC server - and literally discord is not willing to fix it 👍
