### ISSUE TITLE
Discord not detecting PreMiD

### ISSUE THREAD

**Issue by Shinoa6969** [PreMiD/PreMiD#746]
I installed the application and the extension. When its running my discord says "no game detected" in the Activity status tab. I tried to reinstall the app 2 times and it says its connected to my extension but its not showing up

**Comment by viown** [comment]
Make sure to enable "Display current activity as status message" in Settings -> Activity Status

**Comment by Timeraa** [comment]
PreMiD will not be displayed as a Game in the activities tab, it will just work if not our Discord support is the way to go:
https://discord.premid.app > #support
