### ISSUE TITLE
Support For ChromeOS

### ISSUE THREAD

**Issue by Rxann** [PreMiD/PreMiD#750]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem. I would like PreMid to have a ChromeOS build because it would allow people to use PreMid on chromebooks and widen the range of use.

**Describe the solution you'd like**
I would like PreMid to be available for download and use on ChromeOS

**Describe alternatives you've considered**
I have considered using a VM or changing the OS to Linux or Windows.

**Additional context**
No other context.

**Comment by ririxidev** [comment]
We already know about it, should happen with V3 but probably will lack support for applications, who knows.
