### ISSUE TITLE
Edge Extension won't add presences from Store

### ISSUE THREAD

**Issue by Copimox** [PreMiD/PreMiD#753]
When I try to add a presence to the store, it disappears like it's supposed to, but when I open the extension, it's not there. I reload the tab to see that the presence did not add to the extension. I repeat this many times, even deleting and reinstalling both extension and app, but still doesn't work.

**Comment by Timeraa** [comment]
Sorry for the delay, If you still encounter these issues, please join our [Discord](https://discord.premid.app) and open a support ticket in #support.
