### ISSUE TITLE
Khan Academy Support

### ISSUE THREAD

**Issue by Khosraw** [PreMiD/PreMiD#767]
**Is your feature request related to a problem? Please describe.**
I was very surprised that so many websites made it to PreMID except for Khan Academy. I wanted to show off the fact that I was learning Algebra II. ;)

**Describe the solution you'd like**
I mean you could just add support for the website. Sadly I'm not entirely sure what the process looks like or if you have a simple API you use to do it. However, I think it would be very cool.

**Describe alternatives you've considered**
N/A

**Comment by Isa27-0** [comment]
This presence has already been requested in: https://github.com/PreMiD/Presences/issues/751
