### ISSUE TITLE
Presence Presence stuck

### ISSUE THREAD

**Issue by lianaling** [PreMiD/PreMiD#769]
**Is your feature request related to a problem? Please describe.**
According to my observations, the PreMid extension displays user's current active tab as the Discord status, but it works very inconsistently. The extension doesn't update sometimes when switching from one active tab to another, e.g. I'm using `Google Meet`, but my Discord status displays `Playing Github`.

**Describe the solution you'd like**
Add a setting for users to set the precedence of active tabs over one another. For example, set YouTube Music as precedence level = 1 (highest), so when the user is using another tab such as Netflix, the Discord status still displays `Playing YouTube Music`.

**Describe alternatives you've considered**
An alternative is write a documentation regarding the precedence rules so that users can tailor their use to the rules.

**Additional context**
`None`

**Comment by Timeraa** [comment]
Hey, PreMiD uses the last active tab that is eligible for having a Presence until you are 5 seconds on another one which can have a Presence, which will then cause PreMiD to switch to that one and so forth. If your status get's stuck (doesn't change even tho you are on a different Tab with a different Presence) it's most likely that Discord rate-limited you and froze your status, just reload Discord by pressing <kbd>CTRL</kbd> + <kbd>R</kbd>. With the upcoming release of v3 we will further improve the way Presences are handled internally which should make this behavior less likely to happen.
