### ISSUE TITLE
2 Browser Windows, No Rich Presence

### ISSUE THREAD

**Issue by BarterClub** [PreMiD/PreMiD#77]
**Describe the bug**
Using more than one screen and you move the tab to the other monitor and it's not the main window for the browser then it will not show rich presence. 
**To Reproduce**
1. open browser
2. open two tabs with the sense one being let's say twitch
3. move tab to other screen. 
4. pick a channel to watch
5. look at discord to see if it works.

**Expected behavior**
Should be showing rich presence. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10663563/50576933-74c67580-0dd1-11e9-93ce-43ec86ecf4f8.png)

**Desktop (please complete the following information):**
 - OS: windows 10 1809
 - Browser: chrome 71.0.3578.98
Newest

**Comment by Timeraa** [comment]
Thats a known issue, i'll try my best to get it to work in the next update!

**Comment by Timeraa** [comment]
Fixed in V2.0

**Comment by alazymeme** [comment]
@Timeraa If the issue's fixed, should the issue not be closed?
