### ISSUE TITLE
Port error everytime i open my PC.

### ISSUE THREAD

**Issue by Nepuu7** [PreMiD/PreMiD#774]
I get the error dialogue in the picture below everytime i login to my PC. PreMiD is already running, that's true but how can i prevent it from running twice? (or more? idk)

![image](https://user-images.githubusercontent.com/61908056/125608830-d9fe3332-7061-4d31-a64b-0055cea51dd3.png)

**Comment by Timeraa** [comment]
PreMiD automatically runs on startup, if you don't open it after logging into your PC, try uninstalling PreMiD, restarting and then see if it still starts, if so uninstall that instance and install PreMiD again.

**Comment by AlexXavier99** [comment]
I have this issue now. What should i do?

**Comment by Nepuu7** [comment]
I don't really remember how I had fixed it but try reinstalling maybe? I am sorry i can't help.
