### ISSUE TITLE
PreMid extension problem

### ISSUE THREAD

**Issue by Avyansh0001** [PreMiD/PreMiD#776]
Today my PreMid extension got deleted automatically from my browser (Edge) and now I am unable to add it back... What is the reason behind the issue? Is it a bug or has my device removed it cause it thought it was a virus or Windows Firewall blocked it?

Regards,
Avyansh Ralph 
Owner of Airdown
https://avyanshralph.netlify.app

**Comment by EncryptedDev** [comment]
Hi, there were complications in the past, but they should be resolved now. If your issue persists, I'd recommend you to sign up to the [PreMiD Beta](https://premid.app/beta) and installing the extension. Feel free to open a ticket on the [PreMiD Discord](https://discord.gg/premid) if you need further help installing the beta extension.
