### ISSUE TITLE
App Doesn't Install On Apple M1

### ISSUE THREAD

**Issue by D1stinct** [PreMiD/PreMiD#779]
![image](https://user-images.githubusercontent.com/68251289/131918181-f20473fd-8562-4f70-899a-b3684fd078d6.png)

**Comment by EncryptedDev** [comment]
Hello! Sorry for the late reply, but there is no reason it shouldn't run on M1. I'm currently using a MBP M1 and it works fine. 

If you have an issue, please join our Discord and we can help you through tickets :)
