### ISSUE TITLE
PreMiD-Store does not work reliably

### ISSUE THREAD

**Issue by phillipoberloher** [PreMiD/PreMiD#782]
Hello folks, 

I've been using PreMiD for a while now, and I'm incredibly happy to have found it. There is only one problem that has been bothering me for a long time: When adding presences, it sometimes hangs very much behind, or is simply removed again. And the problem has been there ever since the new store existed, and is also on my Mac or Windows PC. I've also tried Chrome, Edge and Safari, and the same behaviour with each one. It's incredibly annoying and nerve-wracking.

Issue: Adding presences sometimes very slow/unreliable
My desperate attempts to fix it: 

- Tried multiple platforms (Mac and Windows)
- tried different browsers (Chrome, Edge and Safari) 
- reinstalled the application as well as the extension several times
- waited for a long time, and also waited when adding presences

**Comment by Bas950** [comment]
Simply answer, rate limit.
