### ISSUE TITLE
Tray icon is hard to see

### ISSUE THREAD

**Issue by RoinujNosde** [PreMiD/PreMiD#785]
**Is your feature request related to a problem? Please describe.**
Yes, the tray icon is hard to see on white themes.

**Describe the solution you'd like**
The icon could have a blue background, like the extension's. Or have a dark outline, like Discord's.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/6441328/141686612-afd7d796-95a8-451b-8b5a-5ac171bcbd04.png)

**Comment by EncryptedDev** [comment]
Accessibility will be improved in v3

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
