### ISSUE TITLE
Not showing what anime im watching

### ISSUE THREAD

**Issue by Fecioru** [PreMiD/PreMiD#788]
The site called AnimeKage is not showing the name of anime i'm watching
![Capture](https://user-images.githubusercontent.com/94920087/143059003-5eb915a1-b1f9-4f87-b011-354f406e97d8.PNG)

**Comment by EncryptedDev** [comment]
May have been resolved in PreMiD/Presences#5070; otherwise open an issue in regards to this in PreMiD/Presences instead
