### ISSUE TITLE
Kattis Support

### ISSUE THREAD

**Issue by Khosraw** [PreMiD/PreMiD#792]
**Is your feature request related to a problem? Please describe.**
PreMID does have support for coding websites like CodeWars, but I think Kattis is a pretty popular website as well for solving coding problems. I think it would be cool to be able to show off that you are coding a problem on Kattis. It is not paid as a website or region locked, so being able to scalp data into a RP shouldn't be too difficult either.

**Describe the solution you'd like**
I mean you could just add support for the website. Sadly I'm not entirely sure what the process looks like or if you have a simple API you use to do it. However, I think it would be very cool.

https://open.kattis.com

**Describe alternatives you've considered**
N/A

**Comment by Isa27-0** [comment]
> **Is your feature request related to a problem? Please describe.** PreMID does have support for coding websites like CodeWars, but I think Kattis is a pretty popular website as well for solving coding problems. I think it would be cool to be able to show off that you are coding a problem on Kattis. It is not paid as a website or region locked, so being able to scalp data into a RP shouldn't be too difficult either.

@Khosraw Sorry, here is not to suggest by presences. I recommend creating a [Service Request](https://github.com/PreMiD/Presences/discussions/4658) in [PreMiD/Presences](https://github.com/PreMiD/Presences)
