### ISSUE TITLE
Khan Academy not displaying SAT practice section

### ISSUE THREAD

**Issue by Khosraw** [PreMiD/PreMiD#793]
When going to do SAT practice on the Khan Academy website, it does not show that I am actually doing SAT practice.
![Screenshot_2021-12-21-11-39-25_1920x1080](https://user-images.githubusercontent.com/53713571/147041515-8a12c170-1182-417d-8dba-aae04b29aa40.png)
![Screenshot_2021-12-21-11-38-50_1920x1080](https://user-images.githubusercontent.com/53713571/147041516-8ba69cd1-e8bc-4c9c-a24d-88ee7a2682b9.png)

It does not update the activity and displays whatever was there before.

**Comment by vishyvishal14** [comment]
I use premid too pretty sure its just related to the website addons, or is it?

**Comment by kyrie25** [comment]
This should be moved to [PreMiD/Presences](https://github.com/PreMiD/Presences)
