### ISSUE TITLE
Issues with presence not working at times on macOS

### ISSUE THREAD

**Issue by OfficialCRUGG** [PreMiD/PreMiD#795]
Hey there!

I am running PreMiD v2.2.0 with Extension v2.2.3 (Edge) on macOS Monterey (12.1 Beta 21C5021h) on an M1 MacBook Pro. With this setup, I am experiencing an issue where PreMiD isn't working 90% of the time. Sometimes, it just randomly starts to work out of nowhere. Then e.g. when I skip a song on YTMusic, I see it's not updating. Just the remaining time is going down. After a slight bit, the Presence then disappears.

I already tried rebooting the MacBook, reinstalling the extension, etc., etc.

I'd happily do further and more in-depth debugging steps, just tell me what to do :)

**Comment by EncryptedDev** [comment]
General reliability with PreMiD on macOS is not the greatest, especially the newer versions. We will be looking into creating OS specific releases to improve this in V3

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
