### ISSUE TITLE
PreMiD is not visible in Discord.

### ISSUE THREAD

**Issue by idleboy4038** [PreMiD/PreMiD#796]
I tried PreMiD on both Edge and Chrome but I  #can't see PreMiD in Discord. And also I cant add it manually. But whenever I check PreMiD in the taskbar it is always connected to the Extension.
OS- Windows 11
"Display current activity as status message" in Settings is Enabled.
I have reinstalled both Discord and PreMiD n Extension.

**Comment by mananv1791** [comment]
Hey Rahul,
May be you have turned off your activity status in discord make sure to turn on the activity status and try again.

**Comment by EncryptedDev** [comment]
Open a support ticket in our Discord
