### ISSUE TITLE
Changed browser, PreMiD not showing up on discord.

### ISSUE THREAD

**Issue by BlueMatrixStudios** [PreMiD/PreMiD#797]
I recently switched from opera gx to chrome canary, and PreMiD will not show up on my discord. I reinstalled PreMiD and downloaded the chrome extension, no success.

**Comment by YounglingSlayer9000** [comment]
Same thing happened to me when I switched from Opera GX to Brave, I fixed it by removing the extension from Opera GX and only have it installed on the second browser. Reload PreMiD and check if the tray icon says Extension - Connected when Chrome Canary is running.

**Comment by EncryptedDev** [comment]
This is a client side issue, please open a Support Ticket in the PreMiD Discord
