### ISSUE TITLE
PreMiD app keeps crashing on i3wm

### ISSUE THREAD

**Issue by jonasrdl** [PreMiD/PreMiD#809]
When I try to start Premid it crashes. Error comes as follows:
```
Opened socket
[330883:0224/151023.200102:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
I had the same problem before while installing BetterDiscord. A few others had this problem as well, so I guess it's not just me. There is a workaround (running `premid --no-sandbox`), but I think someone should take a look at this bug.

My [issue](https://github.com/BetterDiscord/BetterDiscord/issues/1235) on BetterDiscord.

Further information:
OS: Garuda Linux
Kernel: 5.16.10-zen1-1-zen
WM: i3wm

**Comment by jonasrdl** [comment]
> This seems to be an Electron issue mentioned in [electron/electron#18265](https://github.com/electron/electron/issues/18265). But since v3 is _not_ going to be written in Electron (from what I've heard), the issue will probably be dealt with once it is published.

Thanks for the info, that'll be all right then. I will still leave the issue open in case others have the same problem.

**Comment by EncryptedDev** [comment]
We will not be fixing this as V3 will be not be using Electron

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
