### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by reyafyi** [PreMiD/PreMiD#813]
**Is your feature request related to a problem? Please describe.**
Currently PreMiD runs on M1 processors through Rosetta and uses much energy. Compiling PreMiD for M1 would fix this

**Describe the solution you'd like**
PreMiD application compiled for M1 Macs

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EncryptedDev** [comment]
Hiya 👋

I totally agree with you as I am a M1 user too. Support for this should be added inV3

**Comment by darkmastermindz** [comment]
@EncryptedDev Could we get the .app packaged signed with a developer identifier in the process of a new package build? Would happy to help with this as well if needed

**Comment by EncryptedDev** [comment]
> @EncryptedDev Could we get the .app packaged signed with a developer identifier in the process of a new package build? Would happy to help with this as well if needed

That requires an Apple Developer license which is a lot of money for a non-profit open-source project

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
