### ISSUE TITLE
Ratelimit exceeded when skipping songs 

### ISSUE THREAD

**Issue by MikeyPantsOn** [PreMiD/PreMiD#814]
I'm trying to use the Premid for Youtube music, I tried Operagx and chrome and both just stop working after I change the song once or twice.

**Comment by KadTheHunter** [comment]
I think this must be what is happening for me as well, it was working fine earlier when I was just listening straight through a playlist, but after skipping a few songs it isn't showing anymore, and no amount of reloading the page/swapping tabs/restarting premid fixes it. Haven't tried rebooting PC yet, will try soon.

**Comment by AztralMenu** [comment]
I opened the same issue a few days ago Dev replied saying this is due a rate limiter should be fixed next update. ( disabling cover art in YTM Presence ) will fix the issue if you plan to skip alot

**Comment by KadTheHunter** [comment]
> I opened the same issue a few days ago Dev replied saying this is due a rate limiter should be fixed next update. ( disabling cover art in YTM Presence ) will fix the issue if you plan to skip alot

Ok thank you, I'll try that :)

**Comment by EncryptedDev** [comment]
This is an issue with Discord ratelimit as previously mentioned which will be fixed in v3

**Comment by Timeraa** [comment]
Can someone try this out with v2.5 and report back? v2.5 fixes lots of ratelimit issues
