### ISSUE TITLE
Music detection for Opera GX users

### ISSUE THREAD

**Issue by notfreitz** [PreMiD/PreMiD#822]
Recently Opera GX has given its users the ability to play music from Apple music, Spotify, Youtube Music, Deezer and Tidal via the sidebar and when using it Premid does not detect any music being played so it does not attach it to your Discord profile. This is just a suggestion for a feature that I think a lot of us would like to see.

**Comment by EncryptedDev** [comment]
This will be looked into when PreMiD v3 is being worked on

**Comment by Timeraa** [comment]
Don't think this is a high priority
