### ISSUE TITLE
Rich Presence stops showing on Discord when changing tabs (Example: YouTube Music)

### ISSUE THREAD

**Issue by Aasteem** [PreMiD/PreMiD#836]
**Bug description**
When listening f.e. to YouTube Music on one tab and then changing to another tab Rich Presence stops showing in Discord.

**Expected behaviour**
Rich Presence always showing on Discord when f.e. listening to music, no matter what tab is the main tab at the moment.

**My computer information**
Windows Version: 10.0.19044 Build 19044
Browser Version (Chrome): 100.0.4896.127 (Official Build) (64-Bit)

**Comment by EncryptedDev** [comment]
Hello 👋

I cannot reproduce this issue, but it could possibly be similar to #814 - please check that instead. If that still doesn't work, open a support ticket in the PreMiD Discord
