### ISSUE TITLE
Get an error when trying to start application on manjaro linux.

### ISSUE THREAD

**Issue by foxrumor** [PreMiD/PreMiD#841]
I get the following response every time I try to launch the premid application.

> Opened socket
> [20423:0501/165957.089665:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
> zsh: trace trap (core dumped)  premid

**Comment by foxrumor** [comment]
I installed premid-git instead of premid from the AUR. The "premid" version is broken.

**Comment by foxrumor** [comment]
I know you guys don't maintain the AUR version here so I left a comment there and flagged it out of date. I've heard from some other Arch users that they have had the same issues after installing from that build.  Hopefully someone will update it or everyone will simply move over to using the -git version after seeing my comment. 

I'm hoping [that version](https://aur.archlinux.org/packages/premid#comment-863804) either gets a new maintainer or is taken down to end the confusion.

**Comment by alexbcberio** [comment]
I had no problems installing premid on arch itself, what version of Manjaro are you using? I'm gonna try replicate the issue on a vm.

The error you mention is quite common on web desktop apps (not PreMiD specific), you can fix it by passing `--no-sandbox` flag or adding this flag to the executable

**Comment by EncryptedDev** [comment]
Inactive
