### ISSUE TITLE
Hide PreMiD text on macOS applet

### ISSUE THREAD

**Issue by pnxl** [PreMiD/PreMiD#842]
**Is your feature request related to a problem? Please describe.**
while maybe fine with shorter titles, with longer titles like this it sure does make the menu bar look very cluttered
i'm not sure if this only happens with youtube tabs, but it seems like it as other presences doesn't show the text

on very long titles the menu bar item just disappears lol

**Describe the solution you'd like**
the ability to hide the text

**Additional context**
![Screenshot 2022-05-03 at 16 19 39](https://user-images.githubusercontent.com/66474423/166430387-b2dac7df-4875-4ac3-ad50-966685a12b93.png)

**Comment by fr0r** [comment]
You can disable this by going to the Extension settings, clicking on your profile picture, then Title Menubar.

**Comment by EncryptedDev** [comment]
The solution above should resolve your issue. If it does not, please open a ticket in our Discord instead
