### ISSUE TITLE
request

### ISSUE THREAD

**Issue by kittenvr** [PreMiD/PreMiD#849]
**Is your feature request related to a problem? Please describe.**
no its a request

**Describe the solution you'd like**
add a customizable rpc but party changes to ur folowers like 998 of 1000 

**Describe alternatives you've considered**
u caan make it update every hour

**Additional context**
<img width="206" alt="168132763-251a813e-1644-4837-91c6-e58ce5eb938f" src="https://user-images.githubusercontent.com/103120356/168469427-2d57fb01-7793-40e5-a9eb-79ddb888b719.png">

**Comment by Timeraa** [comment]
Hey! We have a Presence to have a custom status. It's most likely what you're looking for: https://premid.app/store/presences/Custom%20Status
