### ISSUE TITLE
[Feature request] Add app restart button

### ISSUE THREAD

**Issue by ndbiaw** [PreMiD/PreMiD#857]
**Is your feature request related to a problem? Please describe.**
Sometimes the application stops updating Presence, causing it to freeze. Instead of closing the app and reopening it manually, adding a button for that would be quite helpful.
**Describe the solution you'd like**
Add "Restart" button in application menu

**Describe alternatives you've considered**
Manually close the application and restart it by searching in the Start Menu

**Additional context**

**Comment by EncryptedDev** [comment]
Should be resolved in v3
