### ISSUE TITLE
Addon doesn't exist on Firefox

### ISSUE THREAD

**Issue by TrojanerHD** [PreMiD/PreMiD#86]
**Describe the bug**
Yeah. Firefox says that the addon doesn't exist

**To Reproduce**
1. Open the link [https://addons.mozilla.org/de/firefox/addon/premid/](https://addons.mozilla.org/de/firefox/addon/premid/)
2. Be messed up

**Expected behavior**
The page should show the addon

**Screenshots**
The actual addon-page
- [german](https://user-images.githubusercontent.com/32276754/50731289-13036400-1161-11e9-9362-0e771ad721ca.png)
- [english](https://user-images.githubusercontent.com/32276754/50731313-c3716800-1161-11e9-8fd5-6c16ec1025e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox Quantum 64.0
 - Country: Germany (If that's of any relevance)

**Comment by Fruxh** [comment]
Hey @TrojanerHD,

first of all, thank you so much for the lovely bug report ^^
Firefox disabled/removed our addon from the store.
We're currently trying to figure out what happened and how we could revove it from the dead.
Until then, we have to stay postive and yoi have to download our addon manually.

Thank you again for submitting <3

~Fruxh

**Comment by frozaum** [comment]
also you can try download the firefox version of the extension in the [repository](https://github.com/PreMiD/PreMiD/tree/master) and using on debug mode

**Comment by Copimox** [comment]
> 
> 
> Hey @TrojanerHD,
> 
> first of all, thank you so much for the lovely bug report ^^
> Firefox disabled/removed our addon from the store.
> We're currently trying to figure out what happened and how we could revove it from the dead.
> Until then, we have to stay positive and you have to download our addon manually.
> 
> Thank you again for submitting <3
> 
> ~Fruxh

How do you do that?

**Comment by TrojanerHD** [comment]
Head over to https://docs.premid.app/en/install/firefox and follow the instructions

**Comment by Copimox** [comment]
thanks
