### ISSUE TITLE
Windows installer doesn't prompt or even allow you to set installation path

### ISSUE THREAD

**Issue by girlmaya** [PreMiD/PreMiD#862]
There's not even an install button, it starts installing after hitting "next"

**Comment by EncryptedDev** [comment]
This will be resolved in v3

**Comment by Timeraa** [comment]
We removed this option previously as we had a big issue when you uninstalled the app, will reimplement it soon

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
