### ISSUE TITLE
Discord rich presence stops working after a few seconds while using edge

### ISSUE THREAD

**Issue by broli95** [PreMiD/PreMiD#866]
When I start using either Edge or Edge Canary, PreMiD works for a few seconds, I can see both the track name and the cover art. After a few seconds I can only see "playing Youtube Music", then it disappears completely and doesn't show up anymore. With Opera GX I don't have this kind of problem but there's no Progressive Web App with it.

**Comment by EncryptedDev** [comment]
This should have been fixed in PreMiD/Presences#6518.

If the issue persists, create an issue in PreMiD/Presences
