### ISSUE TITLE
Windows ARM64 Support

### ISSUE THREAD

**Issue by jjjhhhppp** [PreMiD/PreMiD#881]
**Is your feature request related to a problem? Please describe.**
Currently PreMiD, when installed on a device with an ARM64 processor, it runs utilizing x64 emulation and consumes a fair deal of energy. Having PreMiD Windows ARM64 builds would resolve this.

**Describe the solution you'd like**
PreMiD application compiled for Windows ARM64

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EncryptedDev** [comment]
Should be fixed in future versions as we will be removing the requirement for Electron
