### ISSUE TITLE
Premid timesteps bug + extreme spams in console 

### ISSUE THREAD

**Issue by BlueStarBRS** [PreMiD/PreMiD#906]
**Describe the bug**
the timesteps are buggy they go forward instant of back its glitching around same btw with normal stable discord client also premid spams my console full of nonsence

**To Reproduce**
go yt watch a video and go to your profile it might be glitch around

**Expected behavior**
that it counts normaly like 1:34->1:33->1:32 etc.

**Screenshots**
here a video https://streamable.com/fg2vs1

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser Chrome
 - Version 2.2.0
![image](https://user-images.githubusercontent.com/25110093/200723001-88c270ea-92e8-4c83-ad26-35ef964199c9.png)

**Comment by EncryptedDev** [comment]
This is just how the application was made, should be fixed in future versions
