### ISSUE TITLE
(Linux) Application Closing after Launch

### ISSUE THREAD

**Issue by Koyoinu** [PreMiD/PreMiD#919]
**My OS Details**
- OS Name:  Pop!_OS Jammy 22.04 LTS
- OS Type:  64 Bit
- Gnome Version: 42.5
- Windowing System: X11

**My System Specs**
- Processor: Intel Core I7-8700k 3.70GHz x 12
- GPU: Nvidia RTX 2080
- RAM: 32gigs

 **My Issue**
After Launching the Application Manually From my Gnome Dock Menu it pops up on the application section of my dock then disaperes and does not connect to the Premid Extention

**Comment by EncryptedDev** [comment]
A fix was suggested and no response given - please reply if the issue persists.
