### ISSUE TITLE
Choose discord client

### ISSUE THREAD

**Issue by DarkVillager** [PreMiD/PreMiD#928]
**Is your feature request related to a problem? Please describe.**
There are users using multiple clients e.g. PTB & Stable. But they want stable to be picked up by premid.

**Describe the solution you'd like**
So why not add a way to select the client used when there’s more than one.

**Describe alternatives you have considered**
There are none

**Additional context**
n/a

**Comment by Timeraa** [comment]
Too much effort plus now with 2.6 I don't see the need?
