### ISSUE TITLE
Presence not working

### ISSUE THREAD

**Issue by OdarGM** [PreMiD/PreMiD#93]
**Describe the bug**
The presence doesnt work 

**To Reproduce**
1. Install it 
2. Open youtube
3. Not working

**Expected behavior**
IT should work

**Screenshots**
![image](https://media.odar.xyz/Wrw0gIrFo7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by Fruxh** [comment]
Hey @OdarGM,

Thank you for that bug report ^^
Did you install the application too?

Sincerly
~Fruxh

**Comment by OdarGM** [comment]
No i havent installed the appilcation so my PC doesnt lag thats why i am trying to use the chrome version

**Comment by Voknehzyr** [comment]
@OdarGM
