### ISSUE TITLE
Discord Rebranding

### ISSUE THREAD

**Issue by josephisticated** [PreMiD/PreMiD#940]
**Is your feature request related to a problem? Please describe.**
Discord has gotten a re-branding so re-branding the premid website according to it would be nice. oh and some roles are messed up on premid's contributors page.

**Describe the solution you'd like**
a more modern rebranding for everything premid related

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/53388005/221571004-87177e09-479f-4729-ad63-5383564e8fd9.png)

**Comment by EncryptedDev** [comment]
Hey there, @alexbcberio 👋🏼 Could you look into this for me please?

**Comment by alexbcberio** [comment]
Of course! I will take a look at it during the weekend

**Comment by alexbcberio** [comment]
@EncryptedDev, the [PMD-89](https://github.com/PreMiD/Website/tree/PMD-89) branch of the repo should fix the contributors page issue. Though it was already merged. We just should add the `contributors.roles.projectStaff` string as "Project Staff" and it should be fine.

**Comment by alexbcberio** [comment]
Regarding the Discord re-branding I'm not quite updated with all the changes  , they have done quite a lot of things from changing their color palette to their font.

What re-branding changes are you referring to? I'm not as updated as I was on Discord currently.

**Comment by josephisticated** [comment]
Mostly font, logo and color palette change, maybe the background may change as it kind of seems more gaming related.
![image](https://user-images.githubusercontent.com/53388005/226107962-0f4056dc-6301-4ce1-b129-b43a78c67179.png)

**Comment by Timeraa** [comment]
Closing this as I fixed the strings, rebranding not needed as we don't want to be a Discord 1-1 copy cat
