### ISSUE TITLE
Github link in the extension

### ISSUE THREAD

**Issue by DooMl** [PreMiD/PreMiD#95]
**Describe the bug**
The link to Github releases page is actually missing from the extension

**To Reproduce**
1. https://chrome.google.com/webstore/detail/premid/agjnjboanicjcpenljmaaigopkgdnihi
2. Install
3. ( Look at the screenshot bellow )

**Expected behavior**
A link instead of {{github_link}}

**Screenshots**
![image](https://user-images.githubusercontent.com/26717942/51217752-a3903000-1929-11e9-96ca-8911bc56e203.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 x64
 - Browser: Opera
 - Version: 1.3.1.2 ( of browser? 57 )

**Additional context**
Nop

**Comment by DooMl** [comment]
Also the "Get support" button in same page links to a 404 page ( https://premid.app/help )

**Comment by Voknehzyr** [comment]
We already know about that problem, thanks for your issue.
All of these problems will be fixed in upcoming **2.0** release.
