### ISSUE TITLE
Presences not being removed when tab is closed

### ISSUE THREAD

**Issue by KontrollFreek** [PreMiD/PreMiD#954]
**Describe the bug**

Discord Presences are staying after closing a tab, or sometimes duplicating and leaving behind an old version.

**To Reproduce**
1. Open a page supported by PreMiD
2. Do something on that page for around 10 minutes that updates the presence frequently

**Expected behavior**

Presences accurately reflect the browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19044
 - Browser: FireFox 112.0
 - Version: v2.2.0

**Additional context**

**Comment by Celarye** [comment]
+1, I'm having the exact same issue, only thing that fixes it for me is restarting PreMiD or Discord.

**Comment by thepixelmonk** [comment]
Same here, need to restart discord every time I close a tab and want the status cleared. Pretty annoying.

**Comment by KontrollFreek** [comment]
> Same here, need to restart discord every time I close a tab and want the status cleared. Pretty annoying.

You can simply open the tray and quit PreMiD but it still gets very annoying

**Comment by Timeraa** [comment]
App isn't needed anymore and PreMiD is getting more and more stable.
