### ISSUE TITLE
Youtube presence bogged

### ISSUE THREAD

**Issue by Enferlain** [PreMiD/PreMiD#980]
Is it working for anyone? Twitch and youtube music works, but normal youtube doesnt

**Comment by gameshowrecaps** [comment]
Looks like it fixed itself for me.

**Comment by Enferlain** [comment]
Really? What did you do? Still the same for me

**Comment by gameshowrecaps** [comment]
Yeah apparently it doesn't show again as of today.

**Comment by Isa27-0** [comment]
First, visit the [troubleshooting page](https://docs.premid.app/en/troubleshooting), if can't solve it, look for the [presence repository](https://github.com/PreMiD/Presences). This repository here is for the PreMiD application only.
