### ISSUE TITLE
Uninstaller doesn't remove autorun entry

### ISSUE THREAD

**Issue by headquarter8302** [PreMiD/PreMiD#988]
**Describe the bug**
The PreMiD uninstaller doesn't remove the associated autorun entry at `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` on uninstall, requiring the user to either remove the entry by themselves or requiring Windows to restart to remove the entry from Task Manager.

**To Reproduce**
1. Install as usual, doesn't matter whether it's from the official installer or though package managers such as `winget`.
2. Uninstall the program using the uninstaller.

**Expected behavior**
All associated files with PreMiD deleted, along with its autorun entry.

**Screenshots**
Pre-uninstall:
![premid autorun entry normal](https://github.com/PreMiD/PreMiD/assets/65797058/2f502913-c88b-4fae-b2d3-0dd564c4f407)
Post-uninstall:
![premid autorun entry abnormal](https://github.com/PreMiD/PreMiD/assets/65797058/334411e7-144a-417e-8d48-6dc9b2663bee)
Task manager post uninstall:
![image](https://github.com/PreMiD/PreMiD/assets/65797058/bb2a0d33-e723-4878-9eb3-17d4a4a2efb4)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041
 - Browser: Chrome 114.0.5735.110 (64-bit) (cohort: Stable) 
 - Version: 2.2.0

**Additional context**
N/a

**Comment by Timeraa** [comment]
It should do that but App is no longer maintained because it's no longer needed, only the extension.
