### ISSUE TITLE
Extension context invalidated

### ISSUE THREAD

**Issue by RubenPX** [PreMiD/PreMiD#994]
**Describe the bug**

Many time, presence is not working.

**To Reproduce**
1. go to music.youtube.com
2. play any music

**Expected behavior**

I espect extension is sending RPC messages, but instead it drops this error:

```
Uncaught Error: Extension context invalidated.
    at contentScript.ts:48:21
```

error is from `webpack://pmd/src/contentScript.ts`

**Screenshots**

![image](https://github.com/PreMiD/PreMiD/assets/23123160/7c391d60-336a-4351-ab87-c2a92dc11e5e)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Vivaldi 114.0.5735.137
 - Premid App v2.2.0
 - Premid Extension v2.2.3

**Comment by tobycm** [comment]
try refresh tab
