### ISSUE TITLE
Change "is playing" to "is watching"/"is listening to"

### ISSUE THREAD

**Issue by SomaKhaos** [PreMiD/PreMiD#996]
I've just wondered if it would be possible, that premid switches to the respective activity tag, like when you are sites like YouTube, Twitch or crunchyroll, it would say "Is watching" Instead of "is playing a game". Or when you on YT Music or soundcloud for example, it would say "is listening to" instead of "is playing a game".

Would that be possible?

Because in native discord that's possible, so any chances premid could do The same?

**Comment by Isa27-0** [comment]
Unfortunately there is no way, only the presences per partner (Ex: Spotifly) and the bots can change. 

Explanation taken from the Discord server:
![Screenshot_20231027-102333_Discord~2.jpg](https://github.com/PreMiD/PreMiD/assets/68751594/4fbf9c47-d618-415e-91f2-459b88e75fd0)

**Comment by AnimeWaifuGirl** [comment]
spotify dosen't need premid after you connectet your spotify account with discord same for crunchyroll

**Comment by Timeraa** [comment]
This wasn't possible in a ToS friendly way, after lots of discussion with Discord directly they granted us access to this, please check the latest alpha/beta builds, will soon be globally available 2.6.0

**Comment by 2004seraph** [comment]
Hello, sorry if this is not the proper way to do this, but where could I find the alpha builds? I would love to test this

**Comment by Timeraa** [comment]
All accessible in our Discord, beta can be signed up for on https://premid.app/beta and alpha is accessed through being a booster / patron

**Comment by voidwatching** [comment]
> All accessible in our Discord, beta can be signed up for on https://premid.app/beta and alpha is accessed through being a booster / patron

did anything more come of this? i looked at the beta but couldn't find anymore info, just wondering if it's possible at all

**Comment by Timeraa** [comment]
> > All accessible in our Discord, beta can be signed up for on https://premid.app/beta and alpha is accessed through being a booster / patron
> 
> did anything more come of this? i looked at the beta but couldn't find anymore info, just wondering if it's possible at all 

It's long been released to the public
