### ISSUE TITLE
Random connection closed in Linux version

### ISSUE THREAD

**Issue by halldavidwv** [PreMiD/PreMiD#997]
**Describe the bug**
Whenever I open PreMID and let it sit there for few minutes, there's an error popping up called, "Connection Closed" and it will repeat itself for few minutes after creating RPC client

**To Reproduce**
1. I play a YouTube video
2. I open the PreMID mid-way of the video
3. Let it sit until it destroys the RPC client

**Expected behavior**
The program gives an error called, "Connection Closed"

**Screenshots**
![image](https://github.com/PreMiD/PreMiD/assets/98916731/e2367448-74b5-4ac5-b81a-9832597f954e)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser: Firefox
 - Version: 116.0.3

**Comment by KiRura** [comment]
When I start playback on youtube or youtube music after starting premid, I get the same phenomenon.
(I have added the --disable-gpu-sandbox argument to avoid the "GPU process isn't usable." error.)
![Screenshot from 2023-10-12 18-16-29](https://github.com/PreMiD/PreMiD/assets/57588049/4104284a-75ee-4f92-9fea-6044751ac2c9)

Arch Linux 
Chrome Dev 120.0.6051.2

(I used DeepL. Sorry.)

**Comment by Timeraa** [comment]
App isn't needed anymore so this can be closed.
